package com.duzon.ssh.mapper;

import com.duzon.ssh.model.CardUse;
import com.duzon.ssh.model.CardUseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CardUseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int countByExample(CardUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int deleteByExample(CardUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int deleteByPrimaryKey(Integer SEQ);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int insert(CardUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int insertSelective(CardUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    List<CardUse> selectByExample(CardUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    CardUse selectByPrimaryKey(Integer SEQ);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int updateByExampleSelective(@Param("record") CardUse record, @Param("example") CardUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int updateByExample(@Param("record") CardUse record, @Param("example") CardUseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int updateByPrimaryKeySelective(CardUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int updateByPrimaryKey(CardUse record);
}