package com.duzon.ssh.mapper;

import com.duzon.ssh.model.CommonCode;
import com.duzon.ssh.model.CommonCodeExample;
import com.duzon.ssh.model.CommonCodeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommonCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMON_CODE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int countByExample(CommonCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMON_CODE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int deleteByExample(CommonCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMON_CODE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int deleteByPrimaryKey(CommonCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMON_CODE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int insert(CommonCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMON_CODE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int insertSelective(CommonCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMON_CODE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    List<CommonCode> selectByExample(CommonCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMON_CODE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    CommonCode selectByPrimaryKey(CommonCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMON_CODE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int updateByExampleSelective(@Param("record") CommonCode record, @Param("example") CommonCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMON_CODE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int updateByExample(@Param("record") CommonCode record, @Param("example") CommonCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMON_CODE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int updateByPrimaryKeySelective(CommonCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMON_CODE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int updateByPrimaryKey(CommonCode record);
}