package com.duzon.ssh.mapper;

import com.duzon.ssh.model.Cust;
import com.duzon.ssh.model.CustExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int countByExample(CustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int deleteByExample(CustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int deleteByPrimaryKey(String CUST_NO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int insert(Cust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int insertSelective(Cust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    List<Cust> selectByExample(CustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    Cust selectByPrimaryKey(String CUST_NO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int updateByExampleSelective(@Param("record") Cust record, @Param("example") CustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int updateByExample(@Param("record") Cust record, @Param("example") CustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int updateByPrimaryKeySelective(Cust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int updateByPrimaryKey(Cust record);
}