package com.duzon.ssh.mapper;

import com.duzon.ssh.model.Member;
import com.duzon.ssh.model.MemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int countByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int deleteByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int deleteByPrimaryKey(String MEMBER_NO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    List<Member> selectByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    Member selectByPrimaryKey(String MEMBER_NO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int updateByExampleSelective(@Param("record") Member record, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int updateByExample(@Param("record") Member record, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    int updateByPrimaryKey(Member record);
}