package com.duzon.ssh.mapper;

import com.duzon.ssh.model.TbUser;
import com.duzon.ssh.model.TbUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    int countByExample(TbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    int deleteByExample(TbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    int deleteByPrimaryKey(String NO_USER);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    int insert(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    int insertSelective(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    List<TbUser> selectByExample(TbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    TbUser selectByPrimaryKey(String NO_USER);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    int updateByExampleSelective(@Param("record") TbUser record, @Param("example") TbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    int updateByExample(@Param("record") TbUser record, @Param("example") TbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    int updateByPrimaryKeySelective(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    int updateByPrimaryKey(TbUser record);
}