package com.duzon.ssh.model;

public class Card {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD.CARD_ITEM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String CARD_ITEM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD.CARD_NM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String CARD_NM;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD.CARD_ITEM
     *
     * @return the value of CARD.CARD_ITEM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getCARD_ITEM() {
        return CARD_ITEM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD.CARD_ITEM
     *
     * @param CARD_ITEM the value for CARD.CARD_ITEM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setCARD_ITEM(String CARD_ITEM) {
        this.CARD_ITEM = CARD_ITEM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD.CARD_NM
     *
     * @return the value of CARD.CARD_NM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getCARD_NM() {
        return CARD_NM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD.CARD_NM
     *
     * @param CARD_NM the value for CARD.CARD_NM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setCARD_NM(String CARD_NM) {
        this.CARD_NM = CARD_NM;
    }
}