package com.duzon.ssh.model;

import java.math.BigDecimal;
import java.util.Date;

public class CardUse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_USE.SEQ
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private Integer SEQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_USE.CUST_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String CUST_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_USE.CARD_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String CARD_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_USE.USE_DT
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String USE_DT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_USE.TYPE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_USE.AM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private BigDecimal AM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_USE.AM_VAT
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private BigDecimal AM_VAT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_USE.AMT
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private BigDecimal AMT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_USE.REMARK
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String REMARK;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CARD_USE.INSERT_DT
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private Date INSERT_DT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_USE.SEQ
     *
     * @return the value of CARD_USE.SEQ
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public Integer getSEQ() {
        return SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_USE.SEQ
     *
     * @param SEQ the value for CARD_USE.SEQ
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setSEQ(Integer SEQ) {
        this.SEQ = SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_USE.CUST_NO
     *
     * @return the value of CARD_USE.CUST_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getCUST_NO() {
        return CUST_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_USE.CUST_NO
     *
     * @param CUST_NO the value for CARD_USE.CUST_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setCUST_NO(String CUST_NO) {
        this.CUST_NO = CUST_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_USE.CARD_NO
     *
     * @return the value of CARD_USE.CARD_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getCARD_NO() {
        return CARD_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_USE.CARD_NO
     *
     * @param CARD_NO the value for CARD_USE.CARD_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setCARD_NO(String CARD_NO) {
        this.CARD_NO = CARD_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_USE.USE_DT
     *
     * @return the value of CARD_USE.USE_DT
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getUSE_DT() {
        return USE_DT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_USE.USE_DT
     *
     * @param USE_DT the value for CARD_USE.USE_DT
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setUSE_DT(String USE_DT) {
        this.USE_DT = USE_DT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_USE.TYPE
     *
     * @return the value of CARD_USE.TYPE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getTYPE() {
        return TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_USE.TYPE
     *
     * @param TYPE the value for CARD_USE.TYPE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setTYPE(String TYPE) {
        this.TYPE = TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_USE.AM
     *
     * @return the value of CARD_USE.AM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public BigDecimal getAM() {
        return AM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_USE.AM
     *
     * @param AM the value for CARD_USE.AM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setAM(BigDecimal AM) {
        this.AM = AM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_USE.AM_VAT
     *
     * @return the value of CARD_USE.AM_VAT
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public BigDecimal getAM_VAT() {
        return AM_VAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_USE.AM_VAT
     *
     * @param AM_VAT the value for CARD_USE.AM_VAT
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setAM_VAT(BigDecimal AM_VAT) {
        this.AM_VAT = AM_VAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_USE.AMT
     *
     * @return the value of CARD_USE.AMT
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public BigDecimal getAMT() {
        return AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_USE.AMT
     *
     * @param AMT the value for CARD_USE.AMT
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setAMT(BigDecimal AMT) {
        this.AMT = AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_USE.REMARK
     *
     * @return the value of CARD_USE.REMARK
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getREMARK() {
        return REMARK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_USE.REMARK
     *
     * @param REMARK the value for CARD_USE.REMARK
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setREMARK(String REMARK) {
        this.REMARK = REMARK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CARD_USE.INSERT_DT
     *
     * @return the value of CARD_USE.INSERT_DT
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public Date getINSERT_DT() {
        return INSERT_DT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CARD_USE.INSERT_DT
     *
     * @param INSERT_DT the value for CARD_USE.INSERT_DT
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setINSERT_DT(Date INSERT_DT) {
        this.INSERT_DT = INSERT_DT;
    }
}