package com.duzon.ssh.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CardUseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public CardUseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSEQIsNull() {
            addCriterion("SEQ is null");
            return (Criteria) this;
        }

        public Criteria andSEQIsNotNull() {
            addCriterion("SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andSEQEqualTo(Integer value) {
            addCriterion("SEQ =", value, "SEQ");
            return (Criteria) this;
        }

        public Criteria andSEQNotEqualTo(Integer value) {
            addCriterion("SEQ <>", value, "SEQ");
            return (Criteria) this;
        }

        public Criteria andSEQGreaterThan(Integer value) {
            addCriterion("SEQ >", value, "SEQ");
            return (Criteria) this;
        }

        public Criteria andSEQGreaterThanOrEqualTo(Integer value) {
            addCriterion("SEQ >=", value, "SEQ");
            return (Criteria) this;
        }

        public Criteria andSEQLessThan(Integer value) {
            addCriterion("SEQ <", value, "SEQ");
            return (Criteria) this;
        }

        public Criteria andSEQLessThanOrEqualTo(Integer value) {
            addCriterion("SEQ <=", value, "SEQ");
            return (Criteria) this;
        }

        public Criteria andSEQIn(List<Integer> values) {
            addCriterion("SEQ in", values, "SEQ");
            return (Criteria) this;
        }

        public Criteria andSEQNotIn(List<Integer> values) {
            addCriterion("SEQ not in", values, "SEQ");
            return (Criteria) this;
        }

        public Criteria andSEQBetween(Integer value1, Integer value2) {
            addCriterion("SEQ between", value1, value2, "SEQ");
            return (Criteria) this;
        }

        public Criteria andSEQNotBetween(Integer value1, Integer value2) {
            addCriterion("SEQ not between", value1, value2, "SEQ");
            return (Criteria) this;
        }

        public Criteria andCUST_NOIsNull() {
            addCriterion("CUST_NO is null");
            return (Criteria) this;
        }

        public Criteria andCUST_NOIsNotNull() {
            addCriterion("CUST_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCUST_NOEqualTo(String value) {
            addCriterion("CUST_NO =", value, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NONotEqualTo(String value) {
            addCriterion("CUST_NO <>", value, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NOGreaterThan(String value) {
            addCriterion("CUST_NO >", value, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NOGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_NO >=", value, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NOLessThan(String value) {
            addCriterion("CUST_NO <", value, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NOLessThanOrEqualTo(String value) {
            addCriterion("CUST_NO <=", value, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NOLike(String value) {
            addCriterion("CUST_NO like", value, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NONotLike(String value) {
            addCriterion("CUST_NO not like", value, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NOIn(List<String> values) {
            addCriterion("CUST_NO in", values, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NONotIn(List<String> values) {
            addCriterion("CUST_NO not in", values, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NOBetween(String value1, String value2) {
            addCriterion("CUST_NO between", value1, value2, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NONotBetween(String value1, String value2) {
            addCriterion("CUST_NO not between", value1, value2, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCARD_NOIsNull() {
            addCriterion("CARD_NO is null");
            return (Criteria) this;
        }

        public Criteria andCARD_NOIsNotNull() {
            addCriterion("CARD_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCARD_NOEqualTo(String value) {
            addCriterion("CARD_NO =", value, "CARD_NO");
            return (Criteria) this;
        }

        public Criteria andCARD_NONotEqualTo(String value) {
            addCriterion("CARD_NO <>", value, "CARD_NO");
            return (Criteria) this;
        }

        public Criteria andCARD_NOGreaterThan(String value) {
            addCriterion("CARD_NO >", value, "CARD_NO");
            return (Criteria) this;
        }

        public Criteria andCARD_NOGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_NO >=", value, "CARD_NO");
            return (Criteria) this;
        }

        public Criteria andCARD_NOLessThan(String value) {
            addCriterion("CARD_NO <", value, "CARD_NO");
            return (Criteria) this;
        }

        public Criteria andCARD_NOLessThanOrEqualTo(String value) {
            addCriterion("CARD_NO <=", value, "CARD_NO");
            return (Criteria) this;
        }

        public Criteria andCARD_NOLike(String value) {
            addCriterion("CARD_NO like", value, "CARD_NO");
            return (Criteria) this;
        }

        public Criteria andCARD_NONotLike(String value) {
            addCriterion("CARD_NO not like", value, "CARD_NO");
            return (Criteria) this;
        }

        public Criteria andCARD_NOIn(List<String> values) {
            addCriterion("CARD_NO in", values, "CARD_NO");
            return (Criteria) this;
        }

        public Criteria andCARD_NONotIn(List<String> values) {
            addCriterion("CARD_NO not in", values, "CARD_NO");
            return (Criteria) this;
        }

        public Criteria andCARD_NOBetween(String value1, String value2) {
            addCriterion("CARD_NO between", value1, value2, "CARD_NO");
            return (Criteria) this;
        }

        public Criteria andCARD_NONotBetween(String value1, String value2) {
            addCriterion("CARD_NO not between", value1, value2, "CARD_NO");
            return (Criteria) this;
        }

        public Criteria andUSE_DTIsNull() {
            addCriterion("USE_DT is null");
            return (Criteria) this;
        }

        public Criteria andUSE_DTIsNotNull() {
            addCriterion("USE_DT is not null");
            return (Criteria) this;
        }

        public Criteria andUSE_DTEqualTo(String value) {
            addCriterion("USE_DT =", value, "USE_DT");
            return (Criteria) this;
        }

        public Criteria andUSE_DTNotEqualTo(String value) {
            addCriterion("USE_DT <>", value, "USE_DT");
            return (Criteria) this;
        }

        public Criteria andUSE_DTGreaterThan(String value) {
            addCriterion("USE_DT >", value, "USE_DT");
            return (Criteria) this;
        }

        public Criteria andUSE_DTGreaterThanOrEqualTo(String value) {
            addCriterion("USE_DT >=", value, "USE_DT");
            return (Criteria) this;
        }

        public Criteria andUSE_DTLessThan(String value) {
            addCriterion("USE_DT <", value, "USE_DT");
            return (Criteria) this;
        }

        public Criteria andUSE_DTLessThanOrEqualTo(String value) {
            addCriterion("USE_DT <=", value, "USE_DT");
            return (Criteria) this;
        }

        public Criteria andUSE_DTLike(String value) {
            addCriterion("USE_DT like", value, "USE_DT");
            return (Criteria) this;
        }

        public Criteria andUSE_DTNotLike(String value) {
            addCriterion("USE_DT not like", value, "USE_DT");
            return (Criteria) this;
        }

        public Criteria andUSE_DTIn(List<String> values) {
            addCriterion("USE_DT in", values, "USE_DT");
            return (Criteria) this;
        }

        public Criteria andUSE_DTNotIn(List<String> values) {
            addCriterion("USE_DT not in", values, "USE_DT");
            return (Criteria) this;
        }

        public Criteria andUSE_DTBetween(String value1, String value2) {
            addCriterion("USE_DT between", value1, value2, "USE_DT");
            return (Criteria) this;
        }

        public Criteria andUSE_DTNotBetween(String value1, String value2) {
            addCriterion("USE_DT not between", value1, value2, "USE_DT");
            return (Criteria) this;
        }

        public Criteria andTYPEIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTYPEIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTYPEEqualTo(String value) {
            addCriterion("TYPE =", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPENotEqualTo(String value) {
            addCriterion("TYPE <>", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPEGreaterThan(String value) {
            addCriterion("TYPE >", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPEGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE >=", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPELessThan(String value) {
            addCriterion("TYPE <", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPELessThanOrEqualTo(String value) {
            addCriterion("TYPE <=", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPELike(String value) {
            addCriterion("TYPE like", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPENotLike(String value) {
            addCriterion("TYPE not like", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPEIn(List<String> values) {
            addCriterion("TYPE in", values, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPENotIn(List<String> values) {
            addCriterion("TYPE not in", values, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPEBetween(String value1, String value2) {
            addCriterion("TYPE between", value1, value2, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPENotBetween(String value1, String value2) {
            addCriterion("TYPE not between", value1, value2, "TYPE");
            return (Criteria) this;
        }

        public Criteria andAMIsNull() {
            addCriterion("AM is null");
            return (Criteria) this;
        }

        public Criteria andAMIsNotNull() {
            addCriterion("AM is not null");
            return (Criteria) this;
        }

        public Criteria andAMEqualTo(BigDecimal value) {
            addCriterion("AM =", value, "AM");
            return (Criteria) this;
        }

        public Criteria andAMNotEqualTo(BigDecimal value) {
            addCriterion("AM <>", value, "AM");
            return (Criteria) this;
        }

        public Criteria andAMGreaterThan(BigDecimal value) {
            addCriterion("AM >", value, "AM");
            return (Criteria) this;
        }

        public Criteria andAMGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AM >=", value, "AM");
            return (Criteria) this;
        }

        public Criteria andAMLessThan(BigDecimal value) {
            addCriterion("AM <", value, "AM");
            return (Criteria) this;
        }

        public Criteria andAMLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AM <=", value, "AM");
            return (Criteria) this;
        }

        public Criteria andAMIn(List<BigDecimal> values) {
            addCriterion("AM in", values, "AM");
            return (Criteria) this;
        }

        public Criteria andAMNotIn(List<BigDecimal> values) {
            addCriterion("AM not in", values, "AM");
            return (Criteria) this;
        }

        public Criteria andAMBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AM between", value1, value2, "AM");
            return (Criteria) this;
        }

        public Criteria andAMNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AM not between", value1, value2, "AM");
            return (Criteria) this;
        }

        public Criteria andAM_VATIsNull() {
            addCriterion("AM_VAT is null");
            return (Criteria) this;
        }

        public Criteria andAM_VATIsNotNull() {
            addCriterion("AM_VAT is not null");
            return (Criteria) this;
        }

        public Criteria andAM_VATEqualTo(BigDecimal value) {
            addCriterion("AM_VAT =", value, "AM_VAT");
            return (Criteria) this;
        }

        public Criteria andAM_VATNotEqualTo(BigDecimal value) {
            addCriterion("AM_VAT <>", value, "AM_VAT");
            return (Criteria) this;
        }

        public Criteria andAM_VATGreaterThan(BigDecimal value) {
            addCriterion("AM_VAT >", value, "AM_VAT");
            return (Criteria) this;
        }

        public Criteria andAM_VATGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AM_VAT >=", value, "AM_VAT");
            return (Criteria) this;
        }

        public Criteria andAM_VATLessThan(BigDecimal value) {
            addCriterion("AM_VAT <", value, "AM_VAT");
            return (Criteria) this;
        }

        public Criteria andAM_VATLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AM_VAT <=", value, "AM_VAT");
            return (Criteria) this;
        }

        public Criteria andAM_VATIn(List<BigDecimal> values) {
            addCriterion("AM_VAT in", values, "AM_VAT");
            return (Criteria) this;
        }

        public Criteria andAM_VATNotIn(List<BigDecimal> values) {
            addCriterion("AM_VAT not in", values, "AM_VAT");
            return (Criteria) this;
        }

        public Criteria andAM_VATBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AM_VAT between", value1, value2, "AM_VAT");
            return (Criteria) this;
        }

        public Criteria andAM_VATNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AM_VAT not between", value1, value2, "AM_VAT");
            return (Criteria) this;
        }

        public Criteria andAMTIsNull() {
            addCriterion("AMT is null");
            return (Criteria) this;
        }

        public Criteria andAMTIsNotNull() {
            addCriterion("AMT is not null");
            return (Criteria) this;
        }

        public Criteria andAMTEqualTo(BigDecimal value) {
            addCriterion("AMT =", value, "AMT");
            return (Criteria) this;
        }

        public Criteria andAMTNotEqualTo(BigDecimal value) {
            addCriterion("AMT <>", value, "AMT");
            return (Criteria) this;
        }

        public Criteria andAMTGreaterThan(BigDecimal value) {
            addCriterion("AMT >", value, "AMT");
            return (Criteria) this;
        }

        public Criteria andAMTGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AMT >=", value, "AMT");
            return (Criteria) this;
        }

        public Criteria andAMTLessThan(BigDecimal value) {
            addCriterion("AMT <", value, "AMT");
            return (Criteria) this;
        }

        public Criteria andAMTLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AMT <=", value, "AMT");
            return (Criteria) this;
        }

        public Criteria andAMTIn(List<BigDecimal> values) {
            addCriterion("AMT in", values, "AMT");
            return (Criteria) this;
        }

        public Criteria andAMTNotIn(List<BigDecimal> values) {
            addCriterion("AMT not in", values, "AMT");
            return (Criteria) this;
        }

        public Criteria andAMTBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMT between", value1, value2, "AMT");
            return (Criteria) this;
        }

        public Criteria andAMTNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMT not between", value1, value2, "AMT");
            return (Criteria) this;
        }

        public Criteria andREMARKIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andREMARKIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andREMARKEqualTo(String value) {
            addCriterion("REMARK =", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKGreaterThan(String value) {
            addCriterion("REMARK >", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKLessThan(String value) {
            addCriterion("REMARK <", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKLike(String value) {
            addCriterion("REMARK like", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotLike(String value) {
            addCriterion("REMARK not like", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKIn(List<String> values) {
            addCriterion("REMARK in", values, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "REMARK");
            return (Criteria) this;
        }

        public Criteria andINSERT_DTIsNull() {
            addCriterion("INSERT_DT is null");
            return (Criteria) this;
        }

        public Criteria andINSERT_DTIsNotNull() {
            addCriterion("INSERT_DT is not null");
            return (Criteria) this;
        }

        public Criteria andINSERT_DTEqualTo(Date value) {
            addCriterion("INSERT_DT =", value, "INSERT_DT");
            return (Criteria) this;
        }

        public Criteria andINSERT_DTNotEqualTo(Date value) {
            addCriterion("INSERT_DT <>", value, "INSERT_DT");
            return (Criteria) this;
        }

        public Criteria andINSERT_DTGreaterThan(Date value) {
            addCriterion("INSERT_DT >", value, "INSERT_DT");
            return (Criteria) this;
        }

        public Criteria andINSERT_DTGreaterThanOrEqualTo(Date value) {
            addCriterion("INSERT_DT >=", value, "INSERT_DT");
            return (Criteria) this;
        }

        public Criteria andINSERT_DTLessThan(Date value) {
            addCriterion("INSERT_DT <", value, "INSERT_DT");
            return (Criteria) this;
        }

        public Criteria andINSERT_DTLessThanOrEqualTo(Date value) {
            addCriterion("INSERT_DT <=", value, "INSERT_DT");
            return (Criteria) this;
        }

        public Criteria andINSERT_DTIn(List<Date> values) {
            addCriterion("INSERT_DT in", values, "INSERT_DT");
            return (Criteria) this;
        }

        public Criteria andINSERT_DTNotIn(List<Date> values) {
            addCriterion("INSERT_DT not in", values, "INSERT_DT");
            return (Criteria) this;
        }

        public Criteria andINSERT_DTBetween(Date value1, Date value2) {
            addCriterion("INSERT_DT between", value1, value2, "INSERT_DT");
            return (Criteria) this;
        }

        public Criteria andINSERT_DTNotBetween(Date value1, Date value2) {
            addCriterion("INSERT_DT not between", value1, value2, "INSERT_DT");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CARD_USE
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 19 17:56:35 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CARD_USE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}