package com.duzon.ssh.model;

public class CommonCode extends CommonCodeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_CODE.NM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String NM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_CODE.SEQ
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private Short SEQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_CODE.REMARK
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private Object REMARK;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_CODE.NM
     *
     * @return the value of COMMON_CODE.NM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getNM() {
        return NM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_CODE.NM
     *
     * @param NM the value for COMMON_CODE.NM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setNM(String NM) {
        this.NM = NM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_CODE.SEQ
     *
     * @return the value of COMMON_CODE.SEQ
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public Short getSEQ() {
        return SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_CODE.SEQ
     *
     * @param SEQ the value for COMMON_CODE.SEQ
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setSEQ(Short SEQ) {
        this.SEQ = SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_CODE.REMARK
     *
     * @return the value of COMMON_CODE.REMARK
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public Object getREMARK() {
        return REMARK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_CODE.REMARK
     *
     * @param REMARK the value for COMMON_CODE.REMARK
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setREMARK(Object REMARK) {
        this.REMARK = REMARK;
    }
}