package com.duzon.ssh.model;

public class CommonCodeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_CODE.TYPE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_CODE.CD
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String CD;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_CODE.TYPE
     *
     * @return the value of COMMON_CODE.TYPE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getTYPE() {
        return TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_CODE.TYPE
     *
     * @param TYPE the value for COMMON_CODE.TYPE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setTYPE(String TYPE) {
        this.TYPE = TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_CODE.CD
     *
     * @return the value of COMMON_CODE.CD
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getCD() {
        return CD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_CODE.CD
     *
     * @param CD the value for COMMON_CODE.CD
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setCD(String CD) {
        this.CD = CD;
    }
}