package com.duzon.ssh.model;

import java.util.ArrayList;
import java.util.List;

public class CustExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public CustExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCUST_NOIsNull() {
            addCriterion("CUST_NO is null");
            return (Criteria) this;
        }

        public Criteria andCUST_NOIsNotNull() {
            addCriterion("CUST_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCUST_NOEqualTo(String value) {
            addCriterion("CUST_NO =", value, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NONotEqualTo(String value) {
            addCriterion("CUST_NO <>", value, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NOGreaterThan(String value) {
            addCriterion("CUST_NO >", value, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NOGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_NO >=", value, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NOLessThan(String value) {
            addCriterion("CUST_NO <", value, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NOLessThanOrEqualTo(String value) {
            addCriterion("CUST_NO <=", value, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NOLike(String value) {
            addCriterion("CUST_NO like", value, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NONotLike(String value) {
            addCriterion("CUST_NO not like", value, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NOIn(List<String> values) {
            addCriterion("CUST_NO in", values, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NONotIn(List<String> values) {
            addCriterion("CUST_NO not in", values, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NOBetween(String value1, String value2) {
            addCriterion("CUST_NO between", value1, value2, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NONotBetween(String value1, String value2) {
            addCriterion("CUST_NO not between", value1, value2, "CUST_NO");
            return (Criteria) this;
        }

        public Criteria andCUST_NMIsNull() {
            addCriterion("CUST_NM is null");
            return (Criteria) this;
        }

        public Criteria andCUST_NMIsNotNull() {
            addCriterion("CUST_NM is not null");
            return (Criteria) this;
        }

        public Criteria andCUST_NMEqualTo(String value) {
            addCriterion("CUST_NM =", value, "CUST_NM");
            return (Criteria) this;
        }

        public Criteria andCUST_NMNotEqualTo(String value) {
            addCriterion("CUST_NM <>", value, "CUST_NM");
            return (Criteria) this;
        }

        public Criteria andCUST_NMGreaterThan(String value) {
            addCriterion("CUST_NM >", value, "CUST_NM");
            return (Criteria) this;
        }

        public Criteria andCUST_NMGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_NM >=", value, "CUST_NM");
            return (Criteria) this;
        }

        public Criteria andCUST_NMLessThan(String value) {
            addCriterion("CUST_NM <", value, "CUST_NM");
            return (Criteria) this;
        }

        public Criteria andCUST_NMLessThanOrEqualTo(String value) {
            addCriterion("CUST_NM <=", value, "CUST_NM");
            return (Criteria) this;
        }

        public Criteria andCUST_NMLike(String value) {
            addCriterion("CUST_NM like", value, "CUST_NM");
            return (Criteria) this;
        }

        public Criteria andCUST_NMNotLike(String value) {
            addCriterion("CUST_NM not like", value, "CUST_NM");
            return (Criteria) this;
        }

        public Criteria andCUST_NMIn(List<String> values) {
            addCriterion("CUST_NM in", values, "CUST_NM");
            return (Criteria) this;
        }

        public Criteria andCUST_NMNotIn(List<String> values) {
            addCriterion("CUST_NM not in", values, "CUST_NM");
            return (Criteria) this;
        }

        public Criteria andCUST_NMBetween(String value1, String value2) {
            addCriterion("CUST_NM between", value1, value2, "CUST_NM");
            return (Criteria) this;
        }

        public Criteria andCUST_NMNotBetween(String value1, String value2) {
            addCriterion("CUST_NM not between", value1, value2, "CUST_NM");
            return (Criteria) this;
        }

        public Criteria andCUST_TYPEIsNull() {
            addCriterion("CUST_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCUST_TYPEIsNotNull() {
            addCriterion("CUST_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCUST_TYPEEqualTo(String value) {
            addCriterion("CUST_TYPE =", value, "CUST_TYPE");
            return (Criteria) this;
        }

        public Criteria andCUST_TYPENotEqualTo(String value) {
            addCriterion("CUST_TYPE <>", value, "CUST_TYPE");
            return (Criteria) this;
        }

        public Criteria andCUST_TYPEGreaterThan(String value) {
            addCriterion("CUST_TYPE >", value, "CUST_TYPE");
            return (Criteria) this;
        }

        public Criteria andCUST_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_TYPE >=", value, "CUST_TYPE");
            return (Criteria) this;
        }

        public Criteria andCUST_TYPELessThan(String value) {
            addCriterion("CUST_TYPE <", value, "CUST_TYPE");
            return (Criteria) this;
        }

        public Criteria andCUST_TYPELessThanOrEqualTo(String value) {
            addCriterion("CUST_TYPE <=", value, "CUST_TYPE");
            return (Criteria) this;
        }

        public Criteria andCUST_TYPELike(String value) {
            addCriterion("CUST_TYPE like", value, "CUST_TYPE");
            return (Criteria) this;
        }

        public Criteria andCUST_TYPENotLike(String value) {
            addCriterion("CUST_TYPE not like", value, "CUST_TYPE");
            return (Criteria) this;
        }

        public Criteria andCUST_TYPEIn(List<String> values) {
            addCriterion("CUST_TYPE in", values, "CUST_TYPE");
            return (Criteria) this;
        }

        public Criteria andCUST_TYPENotIn(List<String> values) {
            addCriterion("CUST_TYPE not in", values, "CUST_TYPE");
            return (Criteria) this;
        }

        public Criteria andCUST_TYPEBetween(String value1, String value2) {
            addCriterion("CUST_TYPE between", value1, value2, "CUST_TYPE");
            return (Criteria) this;
        }

        public Criteria andCUST_TYPENotBetween(String value1, String value2) {
            addCriterion("CUST_TYPE not between", value1, value2, "CUST_TYPE");
            return (Criteria) this;
        }

        public Criteria andREG_DTIsNull() {
            addCriterion("REG_DT is null");
            return (Criteria) this;
        }

        public Criteria andREG_DTIsNotNull() {
            addCriterion("REG_DT is not null");
            return (Criteria) this;
        }

        public Criteria andREG_DTEqualTo(String value) {
            addCriterion("REG_DT =", value, "REG_DT");
            return (Criteria) this;
        }

        public Criteria andREG_DTNotEqualTo(String value) {
            addCriterion("REG_DT <>", value, "REG_DT");
            return (Criteria) this;
        }

        public Criteria andREG_DTGreaterThan(String value) {
            addCriterion("REG_DT >", value, "REG_DT");
            return (Criteria) this;
        }

        public Criteria andREG_DTGreaterThanOrEqualTo(String value) {
            addCriterion("REG_DT >=", value, "REG_DT");
            return (Criteria) this;
        }

        public Criteria andREG_DTLessThan(String value) {
            addCriterion("REG_DT <", value, "REG_DT");
            return (Criteria) this;
        }

        public Criteria andREG_DTLessThanOrEqualTo(String value) {
            addCriterion("REG_DT <=", value, "REG_DT");
            return (Criteria) this;
        }

        public Criteria andREG_DTLike(String value) {
            addCriterion("REG_DT like", value, "REG_DT");
            return (Criteria) this;
        }

        public Criteria andREG_DTNotLike(String value) {
            addCriterion("REG_DT not like", value, "REG_DT");
            return (Criteria) this;
        }

        public Criteria andREG_DTIn(List<String> values) {
            addCriterion("REG_DT in", values, "REG_DT");
            return (Criteria) this;
        }

        public Criteria andREG_DTNotIn(List<String> values) {
            addCriterion("REG_DT not in", values, "REG_DT");
            return (Criteria) this;
        }

        public Criteria andREG_DTBetween(String value1, String value2) {
            addCriterion("REG_DT between", value1, value2, "REG_DT");
            return (Criteria) this;
        }

        public Criteria andREG_DTNotBetween(String value1, String value2) {
            addCriterion("REG_DT not between", value1, value2, "REG_DT");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CUST
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 19 17:56:35 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CUST
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}