package com.duzon.ssh.model;

public class Cust {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST.CUST_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String CUST_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST.CUST_NM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String CUST_NM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST.CUST_TYPE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String CUST_TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUST.REG_DT
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String REG_DT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST.CUST_NO
     *
     * @return the value of CUST.CUST_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getCUST_NO() {
        return CUST_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST.CUST_NO
     *
     * @param CUST_NO the value for CUST.CUST_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setCUST_NO(String CUST_NO) {
        this.CUST_NO = CUST_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST.CUST_NM
     *
     * @return the value of CUST.CUST_NM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getCUST_NM() {
        return CUST_NM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST.CUST_NM
     *
     * @param CUST_NM the value for CUST.CUST_NM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setCUST_NM(String CUST_NM) {
        this.CUST_NM = CUST_NM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST.CUST_TYPE
     *
     * @return the value of CUST.CUST_TYPE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getCUST_TYPE() {
        return CUST_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST.CUST_TYPE
     *
     * @param CUST_TYPE the value for CUST.CUST_TYPE
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setCUST_TYPE(String CUST_TYPE) {
        this.CUST_TYPE = CUST_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUST.REG_DT
     *
     * @return the value of CUST.REG_DT
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getREG_DT() {
        return REG_DT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUST.REG_DT
     *
     * @param REG_DT the value for CUST.REG_DT
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setREG_DT(String REG_DT) {
        this.REG_DT = REG_DT;
    }
}