package com.duzon.ssh.model;

public class MemberCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_CARD.CARD_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String CARD_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_CARD.MEMBER_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String MEMBER_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_CARD.CARD_ITEM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String CARD_ITEM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER_CARD.USE_YN
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String USE_YN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CARD.CARD_NO
     *
     * @return the value of MEMBER_CARD.CARD_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getCARD_NO() {
        return CARD_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CARD.CARD_NO
     *
     * @param CARD_NO the value for MEMBER_CARD.CARD_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setCARD_NO(String CARD_NO) {
        this.CARD_NO = CARD_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CARD.MEMBER_NO
     *
     * @return the value of MEMBER_CARD.MEMBER_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getMEMBER_NO() {
        return MEMBER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CARD.MEMBER_NO
     *
     * @param MEMBER_NO the value for MEMBER_CARD.MEMBER_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setMEMBER_NO(String MEMBER_NO) {
        this.MEMBER_NO = MEMBER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CARD.CARD_ITEM
     *
     * @return the value of MEMBER_CARD.CARD_ITEM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getCARD_ITEM() {
        return CARD_ITEM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CARD.CARD_ITEM
     *
     * @param CARD_ITEM the value for MEMBER_CARD.CARD_ITEM
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setCARD_ITEM(String CARD_ITEM) {
        this.CARD_ITEM = CARD_ITEM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER_CARD.USE_YN
     *
     * @return the value of MEMBER_CARD.USE_YN
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getUSE_YN() {
        return USE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER_CARD.USE_YN
     *
     * @param USE_YN the value for MEMBER_CARD.USE_YN
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setUSE_YN(String USE_YN) {
        this.USE_YN = USE_YN;
    }
}