package com.duzon.ssh.model;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.MEMBER_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String MEMBER_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.LOGIN_ID
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String LOGIN_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.PASSWORD
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String PASSWORD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.NAME
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    private String NAME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.MEMBER_NO
     *
     * @return the value of MEMBER.MEMBER_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getMEMBER_NO() {
        return MEMBER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.MEMBER_NO
     *
     * @param MEMBER_NO the value for MEMBER.MEMBER_NO
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setMEMBER_NO(String MEMBER_NO) {
        this.MEMBER_NO = MEMBER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.LOGIN_ID
     *
     * @return the value of MEMBER.LOGIN_ID
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getLOGIN_ID() {
        return LOGIN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.LOGIN_ID
     *
     * @param LOGIN_ID the value for MEMBER.LOGIN_ID
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setLOGIN_ID(String LOGIN_ID) {
        this.LOGIN_ID = LOGIN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.PASSWORD
     *
     * @return the value of MEMBER.PASSWORD
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getPASSWORD() {
        return PASSWORD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.PASSWORD
     *
     * @param PASSWORD the value for MEMBER.PASSWORD
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setPASSWORD(String PASSWORD) {
        this.PASSWORD = PASSWORD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.NAME
     *
     * @return the value of MEMBER.NAME
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.NAME
     *
     * @param NAME the value for MEMBER.NAME
     *
     * @mbggenerated Thu Jun 19 17:56:35 KST 2014
     */
    public void setNAME(String NAME) {
        this.NAME = NAME;
    }
}