package com.duzon.ssh.model;

import java.util.ArrayList;
import java.util.List;

public class TbCustExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public TbCustExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNO_CUSTIsNull() {
            addCriterion("NO_CUST is null");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTIsNotNull() {
            addCriterion("NO_CUST is not null");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTEqualTo(String value) {
            addCriterion("NO_CUST =", value, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTNotEqualTo(String value) {
            addCriterion("NO_CUST <>", value, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTGreaterThan(String value) {
            addCriterion("NO_CUST >", value, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTGreaterThanOrEqualTo(String value) {
            addCriterion("NO_CUST >=", value, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTLessThan(String value) {
            addCriterion("NO_CUST <", value, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTLessThanOrEqualTo(String value) {
            addCriterion("NO_CUST <=", value, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTLike(String value) {
            addCriterion("NO_CUST like", value, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTNotLike(String value) {
            addCriterion("NO_CUST not like", value, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTIn(List<String> values) {
            addCriterion("NO_CUST in", values, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTNotIn(List<String> values) {
            addCriterion("NO_CUST not in", values, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTBetween(String value1, String value2) {
            addCriterion("NO_CUST between", value1, value2, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTNotBetween(String value1, String value2) {
            addCriterion("NO_CUST not between", value1, value2, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_IDIsNull() {
            addCriterion("NO_ID is null");
            return (Criteria) this;
        }

        public Criteria andNO_IDIsNotNull() {
            addCriterion("NO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andNO_IDEqualTo(String value) {
            addCriterion("NO_ID =", value, "NO_ID");
            return (Criteria) this;
        }

        public Criteria andNO_IDNotEqualTo(String value) {
            addCriterion("NO_ID <>", value, "NO_ID");
            return (Criteria) this;
        }

        public Criteria andNO_IDGreaterThan(String value) {
            addCriterion("NO_ID >", value, "NO_ID");
            return (Criteria) this;
        }

        public Criteria andNO_IDGreaterThanOrEqualTo(String value) {
            addCriterion("NO_ID >=", value, "NO_ID");
            return (Criteria) this;
        }

        public Criteria andNO_IDLessThan(String value) {
            addCriterion("NO_ID <", value, "NO_ID");
            return (Criteria) this;
        }

        public Criteria andNO_IDLessThanOrEqualTo(String value) {
            addCriterion("NO_ID <=", value, "NO_ID");
            return (Criteria) this;
        }

        public Criteria andNO_IDLike(String value) {
            addCriterion("NO_ID like", value, "NO_ID");
            return (Criteria) this;
        }

        public Criteria andNO_IDNotLike(String value) {
            addCriterion("NO_ID not like", value, "NO_ID");
            return (Criteria) this;
        }

        public Criteria andNO_IDIn(List<String> values) {
            addCriterion("NO_ID in", values, "NO_ID");
            return (Criteria) this;
        }

        public Criteria andNO_IDNotIn(List<String> values) {
            addCriterion("NO_ID not in", values, "NO_ID");
            return (Criteria) this;
        }

        public Criteria andNO_IDBetween(String value1, String value2) {
            addCriterion("NO_ID between", value1, value2, "NO_ID");
            return (Criteria) this;
        }

        public Criteria andNO_IDNotBetween(String value1, String value2) {
            addCriterion("NO_ID not between", value1, value2, "NO_ID");
            return (Criteria) this;
        }

        public Criteria andYN_NONPFIsNull() {
            addCriterion("YN_NONPF is null");
            return (Criteria) this;
        }

        public Criteria andYN_NONPFIsNotNull() {
            addCriterion("YN_NONPF is not null");
            return (Criteria) this;
        }

        public Criteria andYN_NONPFEqualTo(String value) {
            addCriterion("YN_NONPF =", value, "YN_NONPF");
            return (Criteria) this;
        }

        public Criteria andYN_NONPFNotEqualTo(String value) {
            addCriterion("YN_NONPF <>", value, "YN_NONPF");
            return (Criteria) this;
        }

        public Criteria andYN_NONPFGreaterThan(String value) {
            addCriterion("YN_NONPF >", value, "YN_NONPF");
            return (Criteria) this;
        }

        public Criteria andYN_NONPFGreaterThanOrEqualTo(String value) {
            addCriterion("YN_NONPF >=", value, "YN_NONPF");
            return (Criteria) this;
        }

        public Criteria andYN_NONPFLessThan(String value) {
            addCriterion("YN_NONPF <", value, "YN_NONPF");
            return (Criteria) this;
        }

        public Criteria andYN_NONPFLessThanOrEqualTo(String value) {
            addCriterion("YN_NONPF <=", value, "YN_NONPF");
            return (Criteria) this;
        }

        public Criteria andYN_NONPFLike(String value) {
            addCriterion("YN_NONPF like", value, "YN_NONPF");
            return (Criteria) this;
        }

        public Criteria andYN_NONPFNotLike(String value) {
            addCriterion("YN_NONPF not like", value, "YN_NONPF");
            return (Criteria) this;
        }

        public Criteria andYN_NONPFIn(List<String> values) {
            addCriterion("YN_NONPF in", values, "YN_NONPF");
            return (Criteria) this;
        }

        public Criteria andYN_NONPFNotIn(List<String> values) {
            addCriterion("YN_NONPF not in", values, "YN_NONPF");
            return (Criteria) this;
        }

        public Criteria andYN_NONPFBetween(String value1, String value2) {
            addCriterion("YN_NONPF between", value1, value2, "YN_NONPF");
            return (Criteria) this;
        }

        public Criteria andYN_NONPFNotBetween(String value1, String value2) {
            addCriterion("YN_NONPF not between", value1, value2, "YN_NONPF");
            return (Criteria) this;
        }

        public Criteria andNM_CUSTIsNull() {
            addCriterion("NM_CUST is null");
            return (Criteria) this;
        }

        public Criteria andNM_CUSTIsNotNull() {
            addCriterion("NM_CUST is not null");
            return (Criteria) this;
        }

        public Criteria andNM_CUSTEqualTo(String value) {
            addCriterion("NM_CUST =", value, "NM_CUST");
            return (Criteria) this;
        }

        public Criteria andNM_CUSTNotEqualTo(String value) {
            addCriterion("NM_CUST <>", value, "NM_CUST");
            return (Criteria) this;
        }

        public Criteria andNM_CUSTGreaterThan(String value) {
            addCriterion("NM_CUST >", value, "NM_CUST");
            return (Criteria) this;
        }

        public Criteria andNM_CUSTGreaterThanOrEqualTo(String value) {
            addCriterion("NM_CUST >=", value, "NM_CUST");
            return (Criteria) this;
        }

        public Criteria andNM_CUSTLessThan(String value) {
            addCriterion("NM_CUST <", value, "NM_CUST");
            return (Criteria) this;
        }

        public Criteria andNM_CUSTLessThanOrEqualTo(String value) {
            addCriterion("NM_CUST <=", value, "NM_CUST");
            return (Criteria) this;
        }

        public Criteria andNM_CUSTLike(String value) {
            addCriterion("NM_CUST like", value, "NM_CUST");
            return (Criteria) this;
        }

        public Criteria andNM_CUSTNotLike(String value) {
            addCriterion("NM_CUST not like", value, "NM_CUST");
            return (Criteria) this;
        }

        public Criteria andNM_CUSTIn(List<String> values) {
            addCriterion("NM_CUST in", values, "NM_CUST");
            return (Criteria) this;
        }

        public Criteria andNM_CUSTNotIn(List<String> values) {
            addCriterion("NM_CUST not in", values, "NM_CUST");
            return (Criteria) this;
        }

        public Criteria andNM_CUSTBetween(String value1, String value2) {
            addCriterion("NM_CUST between", value1, value2, "NM_CUST");
            return (Criteria) this;
        }

        public Criteria andNM_CUSTNotBetween(String value1, String value2) {
            addCriterion("NM_CUST not between", value1, value2, "NM_CUST");
            return (Criteria) this;
        }

        public Criteria andNM_CEOIsNull() {
            addCriterion("NM_CEO is null");
            return (Criteria) this;
        }

        public Criteria andNM_CEOIsNotNull() {
            addCriterion("NM_CEO is not null");
            return (Criteria) this;
        }

        public Criteria andNM_CEOEqualTo(String value) {
            addCriterion("NM_CEO =", value, "NM_CEO");
            return (Criteria) this;
        }

        public Criteria andNM_CEONotEqualTo(String value) {
            addCriterion("NM_CEO <>", value, "NM_CEO");
            return (Criteria) this;
        }

        public Criteria andNM_CEOGreaterThan(String value) {
            addCriterion("NM_CEO >", value, "NM_CEO");
            return (Criteria) this;
        }

        public Criteria andNM_CEOGreaterThanOrEqualTo(String value) {
            addCriterion("NM_CEO >=", value, "NM_CEO");
            return (Criteria) this;
        }

        public Criteria andNM_CEOLessThan(String value) {
            addCriterion("NM_CEO <", value, "NM_CEO");
            return (Criteria) this;
        }

        public Criteria andNM_CEOLessThanOrEqualTo(String value) {
            addCriterion("NM_CEO <=", value, "NM_CEO");
            return (Criteria) this;
        }

        public Criteria andNM_CEOLike(String value) {
            addCriterion("NM_CEO like", value, "NM_CEO");
            return (Criteria) this;
        }

        public Criteria andNM_CEONotLike(String value) {
            addCriterion("NM_CEO not like", value, "NM_CEO");
            return (Criteria) this;
        }

        public Criteria andNM_CEOIn(List<String> values) {
            addCriterion("NM_CEO in", values, "NM_CEO");
            return (Criteria) this;
        }

        public Criteria andNM_CEONotIn(List<String> values) {
            addCriterion("NM_CEO not in", values, "NM_CEO");
            return (Criteria) this;
        }

        public Criteria andNM_CEOBetween(String value1, String value2) {
            addCriterion("NM_CEO between", value1, value2, "NM_CEO");
            return (Criteria) this;
        }

        public Criteria andNM_CEONotBetween(String value1, String value2) {
            addCriterion("NM_CEO not between", value1, value2, "NM_CEO");
            return (Criteria) this;
        }

        public Criteria andCD_ZIPIsNull() {
            addCriterion("CD_ZIP is null");
            return (Criteria) this;
        }

        public Criteria andCD_ZIPIsNotNull() {
            addCriterion("CD_ZIP is not null");
            return (Criteria) this;
        }

        public Criteria andCD_ZIPEqualTo(String value) {
            addCriterion("CD_ZIP =", value, "CD_ZIP");
            return (Criteria) this;
        }

        public Criteria andCD_ZIPNotEqualTo(String value) {
            addCriterion("CD_ZIP <>", value, "CD_ZIP");
            return (Criteria) this;
        }

        public Criteria andCD_ZIPGreaterThan(String value) {
            addCriterion("CD_ZIP >", value, "CD_ZIP");
            return (Criteria) this;
        }

        public Criteria andCD_ZIPGreaterThanOrEqualTo(String value) {
            addCriterion("CD_ZIP >=", value, "CD_ZIP");
            return (Criteria) this;
        }

        public Criteria andCD_ZIPLessThan(String value) {
            addCriterion("CD_ZIP <", value, "CD_ZIP");
            return (Criteria) this;
        }

        public Criteria andCD_ZIPLessThanOrEqualTo(String value) {
            addCriterion("CD_ZIP <=", value, "CD_ZIP");
            return (Criteria) this;
        }

        public Criteria andCD_ZIPLike(String value) {
            addCriterion("CD_ZIP like", value, "CD_ZIP");
            return (Criteria) this;
        }

        public Criteria andCD_ZIPNotLike(String value) {
            addCriterion("CD_ZIP not like", value, "CD_ZIP");
            return (Criteria) this;
        }

        public Criteria andCD_ZIPIn(List<String> values) {
            addCriterion("CD_ZIP in", values, "CD_ZIP");
            return (Criteria) this;
        }

        public Criteria andCD_ZIPNotIn(List<String> values) {
            addCriterion("CD_ZIP not in", values, "CD_ZIP");
            return (Criteria) this;
        }

        public Criteria andCD_ZIPBetween(String value1, String value2) {
            addCriterion("CD_ZIP between", value1, value2, "CD_ZIP");
            return (Criteria) this;
        }

        public Criteria andCD_ZIPNotBetween(String value1, String value2) {
            addCriterion("CD_ZIP not between", value1, value2, "CD_ZIP");
            return (Criteria) this;
        }

        public Criteria andADDR1IsNull() {
            addCriterion("ADDR1 is null");
            return (Criteria) this;
        }

        public Criteria andADDR1IsNotNull() {
            addCriterion("ADDR1 is not null");
            return (Criteria) this;
        }

        public Criteria andADDR1EqualTo(String value) {
            addCriterion("ADDR1 =", value, "ADDR1");
            return (Criteria) this;
        }

        public Criteria andADDR1NotEqualTo(String value) {
            addCriterion("ADDR1 <>", value, "ADDR1");
            return (Criteria) this;
        }

        public Criteria andADDR1GreaterThan(String value) {
            addCriterion("ADDR1 >", value, "ADDR1");
            return (Criteria) this;
        }

        public Criteria andADDR1GreaterThanOrEqualTo(String value) {
            addCriterion("ADDR1 >=", value, "ADDR1");
            return (Criteria) this;
        }

        public Criteria andADDR1LessThan(String value) {
            addCriterion("ADDR1 <", value, "ADDR1");
            return (Criteria) this;
        }

        public Criteria andADDR1LessThanOrEqualTo(String value) {
            addCriterion("ADDR1 <=", value, "ADDR1");
            return (Criteria) this;
        }

        public Criteria andADDR1Like(String value) {
            addCriterion("ADDR1 like", value, "ADDR1");
            return (Criteria) this;
        }

        public Criteria andADDR1NotLike(String value) {
            addCriterion("ADDR1 not like", value, "ADDR1");
            return (Criteria) this;
        }

        public Criteria andADDR1In(List<String> values) {
            addCriterion("ADDR1 in", values, "ADDR1");
            return (Criteria) this;
        }

        public Criteria andADDR1NotIn(List<String> values) {
            addCriterion("ADDR1 not in", values, "ADDR1");
            return (Criteria) this;
        }

        public Criteria andADDR1Between(String value1, String value2) {
            addCriterion("ADDR1 between", value1, value2, "ADDR1");
            return (Criteria) this;
        }

        public Criteria andADDR1NotBetween(String value1, String value2) {
            addCriterion("ADDR1 not between", value1, value2, "ADDR1");
            return (Criteria) this;
        }

        public Criteria andADDR2IsNull() {
            addCriterion("ADDR2 is null");
            return (Criteria) this;
        }

        public Criteria andADDR2IsNotNull() {
            addCriterion("ADDR2 is not null");
            return (Criteria) this;
        }

        public Criteria andADDR2EqualTo(String value) {
            addCriterion("ADDR2 =", value, "ADDR2");
            return (Criteria) this;
        }

        public Criteria andADDR2NotEqualTo(String value) {
            addCriterion("ADDR2 <>", value, "ADDR2");
            return (Criteria) this;
        }

        public Criteria andADDR2GreaterThan(String value) {
            addCriterion("ADDR2 >", value, "ADDR2");
            return (Criteria) this;
        }

        public Criteria andADDR2GreaterThanOrEqualTo(String value) {
            addCriterion("ADDR2 >=", value, "ADDR2");
            return (Criteria) this;
        }

        public Criteria andADDR2LessThan(String value) {
            addCriterion("ADDR2 <", value, "ADDR2");
            return (Criteria) this;
        }

        public Criteria andADDR2LessThanOrEqualTo(String value) {
            addCriterion("ADDR2 <=", value, "ADDR2");
            return (Criteria) this;
        }

        public Criteria andADDR2Like(String value) {
            addCriterion("ADDR2 like", value, "ADDR2");
            return (Criteria) this;
        }

        public Criteria andADDR2NotLike(String value) {
            addCriterion("ADDR2 not like", value, "ADDR2");
            return (Criteria) this;
        }

        public Criteria andADDR2In(List<String> values) {
            addCriterion("ADDR2 in", values, "ADDR2");
            return (Criteria) this;
        }

        public Criteria andADDR2NotIn(List<String> values) {
            addCriterion("ADDR2 not in", values, "ADDR2");
            return (Criteria) this;
        }

        public Criteria andADDR2Between(String value1, String value2) {
            addCriterion("ADDR2 between", value1, value2, "ADDR2");
            return (Criteria) this;
        }

        public Criteria andADDR2NotBetween(String value1, String value2) {
            addCriterion("ADDR2 not between", value1, value2, "ADDR2");
            return (Criteria) this;
        }

        public Criteria andBIZ_STATUSIsNull() {
            addCriterion("BIZ_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andBIZ_STATUSIsNotNull() {
            addCriterion("BIZ_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andBIZ_STATUSEqualTo(String value) {
            addCriterion("BIZ_STATUS =", value, "BIZ_STATUS");
            return (Criteria) this;
        }

        public Criteria andBIZ_STATUSNotEqualTo(String value) {
            addCriterion("BIZ_STATUS <>", value, "BIZ_STATUS");
            return (Criteria) this;
        }

        public Criteria andBIZ_STATUSGreaterThan(String value) {
            addCriterion("BIZ_STATUS >", value, "BIZ_STATUS");
            return (Criteria) this;
        }

        public Criteria andBIZ_STATUSGreaterThanOrEqualTo(String value) {
            addCriterion("BIZ_STATUS >=", value, "BIZ_STATUS");
            return (Criteria) this;
        }

        public Criteria andBIZ_STATUSLessThan(String value) {
            addCriterion("BIZ_STATUS <", value, "BIZ_STATUS");
            return (Criteria) this;
        }

        public Criteria andBIZ_STATUSLessThanOrEqualTo(String value) {
            addCriterion("BIZ_STATUS <=", value, "BIZ_STATUS");
            return (Criteria) this;
        }

        public Criteria andBIZ_STATUSLike(String value) {
            addCriterion("BIZ_STATUS like", value, "BIZ_STATUS");
            return (Criteria) this;
        }

        public Criteria andBIZ_STATUSNotLike(String value) {
            addCriterion("BIZ_STATUS not like", value, "BIZ_STATUS");
            return (Criteria) this;
        }

        public Criteria andBIZ_STATUSIn(List<String> values) {
            addCriterion("BIZ_STATUS in", values, "BIZ_STATUS");
            return (Criteria) this;
        }

        public Criteria andBIZ_STATUSNotIn(List<String> values) {
            addCriterion("BIZ_STATUS not in", values, "BIZ_STATUS");
            return (Criteria) this;
        }

        public Criteria andBIZ_STATUSBetween(String value1, String value2) {
            addCriterion("BIZ_STATUS between", value1, value2, "BIZ_STATUS");
            return (Criteria) this;
        }

        public Criteria andBIZ_STATUSNotBetween(String value1, String value2) {
            addCriterion("BIZ_STATUS not between", value1, value2, "BIZ_STATUS");
            return (Criteria) this;
        }

        public Criteria andBIZ_TYPEIsNull() {
            addCriterion("BIZ_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andBIZ_TYPEIsNotNull() {
            addCriterion("BIZ_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBIZ_TYPEEqualTo(String value) {
            addCriterion("BIZ_TYPE =", value, "BIZ_TYPE");
            return (Criteria) this;
        }

        public Criteria andBIZ_TYPENotEqualTo(String value) {
            addCriterion("BIZ_TYPE <>", value, "BIZ_TYPE");
            return (Criteria) this;
        }

        public Criteria andBIZ_TYPEGreaterThan(String value) {
            addCriterion("BIZ_TYPE >", value, "BIZ_TYPE");
            return (Criteria) this;
        }

        public Criteria andBIZ_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("BIZ_TYPE >=", value, "BIZ_TYPE");
            return (Criteria) this;
        }

        public Criteria andBIZ_TYPELessThan(String value) {
            addCriterion("BIZ_TYPE <", value, "BIZ_TYPE");
            return (Criteria) this;
        }

        public Criteria andBIZ_TYPELessThanOrEqualTo(String value) {
            addCriterion("BIZ_TYPE <=", value, "BIZ_TYPE");
            return (Criteria) this;
        }

        public Criteria andBIZ_TYPELike(String value) {
            addCriterion("BIZ_TYPE like", value, "BIZ_TYPE");
            return (Criteria) this;
        }

        public Criteria andBIZ_TYPENotLike(String value) {
            addCriterion("BIZ_TYPE not like", value, "BIZ_TYPE");
            return (Criteria) this;
        }

        public Criteria andBIZ_TYPEIn(List<String> values) {
            addCriterion("BIZ_TYPE in", values, "BIZ_TYPE");
            return (Criteria) this;
        }

        public Criteria andBIZ_TYPENotIn(List<String> values) {
            addCriterion("BIZ_TYPE not in", values, "BIZ_TYPE");
            return (Criteria) this;
        }

        public Criteria andBIZ_TYPEBetween(String value1, String value2) {
            addCriterion("BIZ_TYPE between", value1, value2, "BIZ_TYPE");
            return (Criteria) this;
        }

        public Criteria andBIZ_TYPENotBetween(String value1, String value2) {
            addCriterion("BIZ_TYPE not between", value1, value2, "BIZ_TYPE");
            return (Criteria) this;
        }

        public Criteria andTEL1IsNull() {
            addCriterion("TEL1 is null");
            return (Criteria) this;
        }

        public Criteria andTEL1IsNotNull() {
            addCriterion("TEL1 is not null");
            return (Criteria) this;
        }

        public Criteria andTEL1EqualTo(String value) {
            addCriterion("TEL1 =", value, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1NotEqualTo(String value) {
            addCriterion("TEL1 <>", value, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1GreaterThan(String value) {
            addCriterion("TEL1 >", value, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1GreaterThanOrEqualTo(String value) {
            addCriterion("TEL1 >=", value, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1LessThan(String value) {
            addCriterion("TEL1 <", value, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1LessThanOrEqualTo(String value) {
            addCriterion("TEL1 <=", value, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1Like(String value) {
            addCriterion("TEL1 like", value, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1NotLike(String value) {
            addCriterion("TEL1 not like", value, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1In(List<String> values) {
            addCriterion("TEL1 in", values, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1NotIn(List<String> values) {
            addCriterion("TEL1 not in", values, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1Between(String value1, String value2) {
            addCriterion("TEL1 between", value1, value2, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1NotBetween(String value1, String value2) {
            addCriterion("TEL1 not between", value1, value2, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL2IsNull() {
            addCriterion("TEL2 is null");
            return (Criteria) this;
        }

        public Criteria andTEL2IsNotNull() {
            addCriterion("TEL2 is not null");
            return (Criteria) this;
        }

        public Criteria andTEL2EqualTo(String value) {
            addCriterion("TEL2 =", value, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2NotEqualTo(String value) {
            addCriterion("TEL2 <>", value, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2GreaterThan(String value) {
            addCriterion("TEL2 >", value, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2GreaterThanOrEqualTo(String value) {
            addCriterion("TEL2 >=", value, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2LessThan(String value) {
            addCriterion("TEL2 <", value, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2LessThanOrEqualTo(String value) {
            addCriterion("TEL2 <=", value, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2Like(String value) {
            addCriterion("TEL2 like", value, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2NotLike(String value) {
            addCriterion("TEL2 not like", value, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2In(List<String> values) {
            addCriterion("TEL2 in", values, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2NotIn(List<String> values) {
            addCriterion("TEL2 not in", values, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2Between(String value1, String value2) {
            addCriterion("TEL2 between", value1, value2, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2NotBetween(String value1, String value2) {
            addCriterion("TEL2 not between", value1, value2, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL3IsNull() {
            addCriterion("TEL3 is null");
            return (Criteria) this;
        }

        public Criteria andTEL3IsNotNull() {
            addCriterion("TEL3 is not null");
            return (Criteria) this;
        }

        public Criteria andTEL3EqualTo(String value) {
            addCriterion("TEL3 =", value, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3NotEqualTo(String value) {
            addCriterion("TEL3 <>", value, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3GreaterThan(String value) {
            addCriterion("TEL3 >", value, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3GreaterThanOrEqualTo(String value) {
            addCriterion("TEL3 >=", value, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3LessThan(String value) {
            addCriterion("TEL3 <", value, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3LessThanOrEqualTo(String value) {
            addCriterion("TEL3 <=", value, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3Like(String value) {
            addCriterion("TEL3 like", value, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3NotLike(String value) {
            addCriterion("TEL3 not like", value, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3In(List<String> values) {
            addCriterion("TEL3 in", values, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3NotIn(List<String> values) {
            addCriterion("TEL3 not in", values, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3Between(String value1, String value2) {
            addCriterion("TEL3 between", value1, value2, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3NotBetween(String value1, String value2) {
            addCriterion("TEL3 not between", value1, value2, "TEL3");
            return (Criteria) this;
        }

        public Criteria andFAX1IsNull() {
            addCriterion("FAX1 is null");
            return (Criteria) this;
        }

        public Criteria andFAX1IsNotNull() {
            addCriterion("FAX1 is not null");
            return (Criteria) this;
        }

        public Criteria andFAX1EqualTo(String value) {
            addCriterion("FAX1 =", value, "FAX1");
            return (Criteria) this;
        }

        public Criteria andFAX1NotEqualTo(String value) {
            addCriterion("FAX1 <>", value, "FAX1");
            return (Criteria) this;
        }

        public Criteria andFAX1GreaterThan(String value) {
            addCriterion("FAX1 >", value, "FAX1");
            return (Criteria) this;
        }

        public Criteria andFAX1GreaterThanOrEqualTo(String value) {
            addCriterion("FAX1 >=", value, "FAX1");
            return (Criteria) this;
        }

        public Criteria andFAX1LessThan(String value) {
            addCriterion("FAX1 <", value, "FAX1");
            return (Criteria) this;
        }

        public Criteria andFAX1LessThanOrEqualTo(String value) {
            addCriterion("FAX1 <=", value, "FAX1");
            return (Criteria) this;
        }

        public Criteria andFAX1Like(String value) {
            addCriterion("FAX1 like", value, "FAX1");
            return (Criteria) this;
        }

        public Criteria andFAX1NotLike(String value) {
            addCriterion("FAX1 not like", value, "FAX1");
            return (Criteria) this;
        }

        public Criteria andFAX1In(List<String> values) {
            addCriterion("FAX1 in", values, "FAX1");
            return (Criteria) this;
        }

        public Criteria andFAX1NotIn(List<String> values) {
            addCriterion("FAX1 not in", values, "FAX1");
            return (Criteria) this;
        }

        public Criteria andFAX1Between(String value1, String value2) {
            addCriterion("FAX1 between", value1, value2, "FAX1");
            return (Criteria) this;
        }

        public Criteria andFAX1NotBetween(String value1, String value2) {
            addCriterion("FAX1 not between", value1, value2, "FAX1");
            return (Criteria) this;
        }

        public Criteria andFAX2IsNull() {
            addCriterion("FAX2 is null");
            return (Criteria) this;
        }

        public Criteria andFAX2IsNotNull() {
            addCriterion("FAX2 is not null");
            return (Criteria) this;
        }

        public Criteria andFAX2EqualTo(String value) {
            addCriterion("FAX2 =", value, "FAX2");
            return (Criteria) this;
        }

        public Criteria andFAX2NotEqualTo(String value) {
            addCriterion("FAX2 <>", value, "FAX2");
            return (Criteria) this;
        }

        public Criteria andFAX2GreaterThan(String value) {
            addCriterion("FAX2 >", value, "FAX2");
            return (Criteria) this;
        }

        public Criteria andFAX2GreaterThanOrEqualTo(String value) {
            addCriterion("FAX2 >=", value, "FAX2");
            return (Criteria) this;
        }

        public Criteria andFAX2LessThan(String value) {
            addCriterion("FAX2 <", value, "FAX2");
            return (Criteria) this;
        }

        public Criteria andFAX2LessThanOrEqualTo(String value) {
            addCriterion("FAX2 <=", value, "FAX2");
            return (Criteria) this;
        }

        public Criteria andFAX2Like(String value) {
            addCriterion("FAX2 like", value, "FAX2");
            return (Criteria) this;
        }

        public Criteria andFAX2NotLike(String value) {
            addCriterion("FAX2 not like", value, "FAX2");
            return (Criteria) this;
        }

        public Criteria andFAX2In(List<String> values) {
            addCriterion("FAX2 in", values, "FAX2");
            return (Criteria) this;
        }

        public Criteria andFAX2NotIn(List<String> values) {
            addCriterion("FAX2 not in", values, "FAX2");
            return (Criteria) this;
        }

        public Criteria andFAX2Between(String value1, String value2) {
            addCriterion("FAX2 between", value1, value2, "FAX2");
            return (Criteria) this;
        }

        public Criteria andFAX2NotBetween(String value1, String value2) {
            addCriterion("FAX2 not between", value1, value2, "FAX2");
            return (Criteria) this;
        }

        public Criteria andFAX3IsNull() {
            addCriterion("FAX3 is null");
            return (Criteria) this;
        }

        public Criteria andFAX3IsNotNull() {
            addCriterion("FAX3 is not null");
            return (Criteria) this;
        }

        public Criteria andFAX3EqualTo(String value) {
            addCriterion("FAX3 =", value, "FAX3");
            return (Criteria) this;
        }

        public Criteria andFAX3NotEqualTo(String value) {
            addCriterion("FAX3 <>", value, "FAX3");
            return (Criteria) this;
        }

        public Criteria andFAX3GreaterThan(String value) {
            addCriterion("FAX3 >", value, "FAX3");
            return (Criteria) this;
        }

        public Criteria andFAX3GreaterThanOrEqualTo(String value) {
            addCriterion("FAX3 >=", value, "FAX3");
            return (Criteria) this;
        }

        public Criteria andFAX3LessThan(String value) {
            addCriterion("FAX3 <", value, "FAX3");
            return (Criteria) this;
        }

        public Criteria andFAX3LessThanOrEqualTo(String value) {
            addCriterion("FAX3 <=", value, "FAX3");
            return (Criteria) this;
        }

        public Criteria andFAX3Like(String value) {
            addCriterion("FAX3 like", value, "FAX3");
            return (Criteria) this;
        }

        public Criteria andFAX3NotLike(String value) {
            addCriterion("FAX3 not like", value, "FAX3");
            return (Criteria) this;
        }

        public Criteria andFAX3In(List<String> values) {
            addCriterion("FAX3 in", values, "FAX3");
            return (Criteria) this;
        }

        public Criteria andFAX3NotIn(List<String> values) {
            addCriterion("FAX3 not in", values, "FAX3");
            return (Criteria) this;
        }

        public Criteria andFAX3Between(String value1, String value2) {
            addCriterion("FAX3 between", value1, value2, "FAX3");
            return (Criteria) this;
        }

        public Criteria andFAX3NotBetween(String value1, String value2) {
            addCriterion("FAX3 not between", value1, value2, "FAX3");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTIsNull() {
            addCriterion("NO_ACCT is null");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTIsNotNull() {
            addCriterion("NO_ACCT is not null");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTEqualTo(String value) {
            addCriterion("NO_ACCT =", value, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTNotEqualTo(String value) {
            addCriterion("NO_ACCT <>", value, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTGreaterThan(String value) {
            addCriterion("NO_ACCT >", value, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTGreaterThanOrEqualTo(String value) {
            addCriterion("NO_ACCT >=", value, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTLessThan(String value) {
            addCriterion("NO_ACCT <", value, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTLessThanOrEqualTo(String value) {
            addCriterion("NO_ACCT <=", value, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTLike(String value) {
            addCriterion("NO_ACCT like", value, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTNotLike(String value) {
            addCriterion("NO_ACCT not like", value, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTIn(List<String> values) {
            addCriterion("NO_ACCT in", values, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTNotIn(List<String> values) {
            addCriterion("NO_ACCT not in", values, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTBetween(String value1, String value2) {
            addCriterion("NO_ACCT between", value1, value2, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTNotBetween(String value1, String value2) {
            addCriterion("NO_ACCT not between", value1, value2, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andFG_CUSTIsNull() {
            addCriterion("FG_CUST is null");
            return (Criteria) this;
        }

        public Criteria andFG_CUSTIsNotNull() {
            addCriterion("FG_CUST is not null");
            return (Criteria) this;
        }

        public Criteria andFG_CUSTEqualTo(String value) {
            addCriterion("FG_CUST =", value, "FG_CUST");
            return (Criteria) this;
        }

        public Criteria andFG_CUSTNotEqualTo(String value) {
            addCriterion("FG_CUST <>", value, "FG_CUST");
            return (Criteria) this;
        }

        public Criteria andFG_CUSTGreaterThan(String value) {
            addCriterion("FG_CUST >", value, "FG_CUST");
            return (Criteria) this;
        }

        public Criteria andFG_CUSTGreaterThanOrEqualTo(String value) {
            addCriterion("FG_CUST >=", value, "FG_CUST");
            return (Criteria) this;
        }

        public Criteria andFG_CUSTLessThan(String value) {
            addCriterion("FG_CUST <", value, "FG_CUST");
            return (Criteria) this;
        }

        public Criteria andFG_CUSTLessThanOrEqualTo(String value) {
            addCriterion("FG_CUST <=", value, "FG_CUST");
            return (Criteria) this;
        }

        public Criteria andFG_CUSTLike(String value) {
            addCriterion("FG_CUST like", value, "FG_CUST");
            return (Criteria) this;
        }

        public Criteria andFG_CUSTNotLike(String value) {
            addCriterion("FG_CUST not like", value, "FG_CUST");
            return (Criteria) this;
        }

        public Criteria andFG_CUSTIn(List<String> values) {
            addCriterion("FG_CUST in", values, "FG_CUST");
            return (Criteria) this;
        }

        public Criteria andFG_CUSTNotIn(List<String> values) {
            addCriterion("FG_CUST not in", values, "FG_CUST");
            return (Criteria) this;
        }

        public Criteria andFG_CUSTBetween(String value1, String value2) {
            addCriterion("FG_CUST between", value1, value2, "FG_CUST");
            return (Criteria) this;
        }

        public Criteria andFG_CUSTNotBetween(String value1, String value2) {
            addCriterion("FG_CUST not between", value1, value2, "FG_CUST");
            return (Criteria) this;
        }

        public Criteria andFG_PAYIsNull() {
            addCriterion("FG_PAY is null");
            return (Criteria) this;
        }

        public Criteria andFG_PAYIsNotNull() {
            addCriterion("FG_PAY is not null");
            return (Criteria) this;
        }

        public Criteria andFG_PAYEqualTo(String value) {
            addCriterion("FG_PAY =", value, "FG_PAY");
            return (Criteria) this;
        }

        public Criteria andFG_PAYNotEqualTo(String value) {
            addCriterion("FG_PAY <>", value, "FG_PAY");
            return (Criteria) this;
        }

        public Criteria andFG_PAYGreaterThan(String value) {
            addCriterion("FG_PAY >", value, "FG_PAY");
            return (Criteria) this;
        }

        public Criteria andFG_PAYGreaterThanOrEqualTo(String value) {
            addCriterion("FG_PAY >=", value, "FG_PAY");
            return (Criteria) this;
        }

        public Criteria andFG_PAYLessThan(String value) {
            addCriterion("FG_PAY <", value, "FG_PAY");
            return (Criteria) this;
        }

        public Criteria andFG_PAYLessThanOrEqualTo(String value) {
            addCriterion("FG_PAY <=", value, "FG_PAY");
            return (Criteria) this;
        }

        public Criteria andFG_PAYLike(String value) {
            addCriterion("FG_PAY like", value, "FG_PAY");
            return (Criteria) this;
        }

        public Criteria andFG_PAYNotLike(String value) {
            addCriterion("FG_PAY not like", value, "FG_PAY");
            return (Criteria) this;
        }

        public Criteria andFG_PAYIn(List<String> values) {
            addCriterion("FG_PAY in", values, "FG_PAY");
            return (Criteria) this;
        }

        public Criteria andFG_PAYNotIn(List<String> values) {
            addCriterion("FG_PAY not in", values, "FG_PAY");
            return (Criteria) this;
        }

        public Criteria andFG_PAYBetween(String value1, String value2) {
            addCriterion("FG_PAY between", value1, value2, "FG_PAY");
            return (Criteria) this;
        }

        public Criteria andFG_PAYNotBetween(String value1, String value2) {
            addCriterion("FG_PAY not between", value1, value2, "FG_PAY");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USEREqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERLike(String value) {
            addCriterion("UPDATE_USER like", value, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATEIsNull() {
            addCriterion("DT_UPDATE is null");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATEIsNotNull() {
            addCriterion("DT_UPDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATEEqualTo(String value) {
            addCriterion("DT_UPDATE =", value, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATENotEqualTo(String value) {
            addCriterion("DT_UPDATE <>", value, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATEGreaterThan(String value) {
            addCriterion("DT_UPDATE >", value, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATEGreaterThanOrEqualTo(String value) {
            addCriterion("DT_UPDATE >=", value, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATELessThan(String value) {
            addCriterion("DT_UPDATE <", value, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATELessThanOrEqualTo(String value) {
            addCriterion("DT_UPDATE <=", value, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATELike(String value) {
            addCriterion("DT_UPDATE like", value, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATENotLike(String value) {
            addCriterion("DT_UPDATE not like", value, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATEIn(List<String> values) {
            addCriterion("DT_UPDATE in", values, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATENotIn(List<String> values) {
            addCriterion("DT_UPDATE not in", values, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATEBetween(String value1, String value2) {
            addCriterion("DT_UPDATE between", value1, value2, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATENotBetween(String value1, String value2) {
            addCriterion("DT_UPDATE not between", value1, value2, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERIsNull() {
            addCriterion("DT_ENTER is null");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERIsNotNull() {
            addCriterion("DT_ENTER is not null");
            return (Criteria) this;
        }

        public Criteria andDT_ENTEREqualTo(String value) {
            addCriterion("DT_ENTER =", value, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERNotEqualTo(String value) {
            addCriterion("DT_ENTER <>", value, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERGreaterThan(String value) {
            addCriterion("DT_ENTER >", value, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERGreaterThanOrEqualTo(String value) {
            addCriterion("DT_ENTER >=", value, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERLessThan(String value) {
            addCriterion("DT_ENTER <", value, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERLessThanOrEqualTo(String value) {
            addCriterion("DT_ENTER <=", value, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERLike(String value) {
            addCriterion("DT_ENTER like", value, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERNotLike(String value) {
            addCriterion("DT_ENTER not like", value, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERIn(List<String> values) {
            addCriterion("DT_ENTER in", values, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERNotIn(List<String> values) {
            addCriterion("DT_ENTER not in", values, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERBetween(String value1, String value2) {
            addCriterion("DT_ENTER between", value1, value2, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERNotBetween(String value1, String value2) {
            addCriterion("DT_ENTER not between", value1, value2, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andYN_CSMTIsNull() {
            addCriterion("YN_CSMT is null");
            return (Criteria) this;
        }

        public Criteria andYN_CSMTIsNotNull() {
            addCriterion("YN_CSMT is not null");
            return (Criteria) this;
        }

        public Criteria andYN_CSMTEqualTo(String value) {
            addCriterion("YN_CSMT =", value, "YN_CSMT");
            return (Criteria) this;
        }

        public Criteria andYN_CSMTNotEqualTo(String value) {
            addCriterion("YN_CSMT <>", value, "YN_CSMT");
            return (Criteria) this;
        }

        public Criteria andYN_CSMTGreaterThan(String value) {
            addCriterion("YN_CSMT >", value, "YN_CSMT");
            return (Criteria) this;
        }

        public Criteria andYN_CSMTGreaterThanOrEqualTo(String value) {
            addCriterion("YN_CSMT >=", value, "YN_CSMT");
            return (Criteria) this;
        }

        public Criteria andYN_CSMTLessThan(String value) {
            addCriterion("YN_CSMT <", value, "YN_CSMT");
            return (Criteria) this;
        }

        public Criteria andYN_CSMTLessThanOrEqualTo(String value) {
            addCriterion("YN_CSMT <=", value, "YN_CSMT");
            return (Criteria) this;
        }

        public Criteria andYN_CSMTLike(String value) {
            addCriterion("YN_CSMT like", value, "YN_CSMT");
            return (Criteria) this;
        }

        public Criteria andYN_CSMTNotLike(String value) {
            addCriterion("YN_CSMT not like", value, "YN_CSMT");
            return (Criteria) this;
        }

        public Criteria andYN_CSMTIn(List<String> values) {
            addCriterion("YN_CSMT in", values, "YN_CSMT");
            return (Criteria) this;
        }

        public Criteria andYN_CSMTNotIn(List<String> values) {
            addCriterion("YN_CSMT not in", values, "YN_CSMT");
            return (Criteria) this;
        }

        public Criteria andYN_CSMTBetween(String value1, String value2) {
            addCriterion("YN_CSMT between", value1, value2, "YN_CSMT");
            return (Criteria) this;
        }

        public Criteria andYN_CSMTNotBetween(String value1, String value2) {
            addCriterion("YN_CSMT not between", value1, value2, "YN_CSMT");
            return (Criteria) this;
        }

        public Criteria andCD_ERPIsNull() {
            addCriterion("CD_ERP is null");
            return (Criteria) this;
        }

        public Criteria andCD_ERPIsNotNull() {
            addCriterion("CD_ERP is not null");
            return (Criteria) this;
        }

        public Criteria andCD_ERPEqualTo(String value) {
            addCriterion("CD_ERP =", value, "CD_ERP");
            return (Criteria) this;
        }

        public Criteria andCD_ERPNotEqualTo(String value) {
            addCriterion("CD_ERP <>", value, "CD_ERP");
            return (Criteria) this;
        }

        public Criteria andCD_ERPGreaterThan(String value) {
            addCriterion("CD_ERP >", value, "CD_ERP");
            return (Criteria) this;
        }

        public Criteria andCD_ERPGreaterThanOrEqualTo(String value) {
            addCriterion("CD_ERP >=", value, "CD_ERP");
            return (Criteria) this;
        }

        public Criteria andCD_ERPLessThan(String value) {
            addCriterion("CD_ERP <", value, "CD_ERP");
            return (Criteria) this;
        }

        public Criteria andCD_ERPLessThanOrEqualTo(String value) {
            addCriterion("CD_ERP <=", value, "CD_ERP");
            return (Criteria) this;
        }

        public Criteria andCD_ERPLike(String value) {
            addCriterion("CD_ERP like", value, "CD_ERP");
            return (Criteria) this;
        }

        public Criteria andCD_ERPNotLike(String value) {
            addCriterion("CD_ERP not like", value, "CD_ERP");
            return (Criteria) this;
        }

        public Criteria andCD_ERPIn(List<String> values) {
            addCriterion("CD_ERP in", values, "CD_ERP");
            return (Criteria) this;
        }

        public Criteria andCD_ERPNotIn(List<String> values) {
            addCriterion("CD_ERP not in", values, "CD_ERP");
            return (Criteria) this;
        }

        public Criteria andCD_ERPBetween(String value1, String value2) {
            addCriterion("CD_ERP between", value1, value2, "CD_ERP");
            return (Criteria) this;
        }

        public Criteria andCD_ERPNotBetween(String value1, String value2) {
            addCriterion("CD_ERP not between", value1, value2, "CD_ERP");
            return (Criteria) this;
        }

        public Criteria andYN_DELIsNull() {
            addCriterion("YN_DEL is null");
            return (Criteria) this;
        }

        public Criteria andYN_DELIsNotNull() {
            addCriterion("YN_DEL is not null");
            return (Criteria) this;
        }

        public Criteria andYN_DELEqualTo(String value) {
            addCriterion("YN_DEL =", value, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELNotEqualTo(String value) {
            addCriterion("YN_DEL <>", value, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELGreaterThan(String value) {
            addCriterion("YN_DEL >", value, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELGreaterThanOrEqualTo(String value) {
            addCriterion("YN_DEL >=", value, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELLessThan(String value) {
            addCriterion("YN_DEL <", value, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELLessThanOrEqualTo(String value) {
            addCriterion("YN_DEL <=", value, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELLike(String value) {
            addCriterion("YN_DEL like", value, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELNotLike(String value) {
            addCriterion("YN_DEL not like", value, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELIn(List<String> values) {
            addCriterion("YN_DEL in", values, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELNotIn(List<String> values) {
            addCriterion("YN_DEL not in", values, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELBetween(String value1, String value2) {
            addCriterion("YN_DEL between", value1, value2, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELNotBetween(String value1, String value2) {
            addCriterion("YN_DEL not between", value1, value2, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_JNLIsNull() {
            addCriterion("YN_JNL is null");
            return (Criteria) this;
        }

        public Criteria andYN_JNLIsNotNull() {
            addCriterion("YN_JNL is not null");
            return (Criteria) this;
        }

        public Criteria andYN_JNLEqualTo(String value) {
            addCriterion("YN_JNL =", value, "YN_JNL");
            return (Criteria) this;
        }

        public Criteria andYN_JNLNotEqualTo(String value) {
            addCriterion("YN_JNL <>", value, "YN_JNL");
            return (Criteria) this;
        }

        public Criteria andYN_JNLGreaterThan(String value) {
            addCriterion("YN_JNL >", value, "YN_JNL");
            return (Criteria) this;
        }

        public Criteria andYN_JNLGreaterThanOrEqualTo(String value) {
            addCriterion("YN_JNL >=", value, "YN_JNL");
            return (Criteria) this;
        }

        public Criteria andYN_JNLLessThan(String value) {
            addCriterion("YN_JNL <", value, "YN_JNL");
            return (Criteria) this;
        }

        public Criteria andYN_JNLLessThanOrEqualTo(String value) {
            addCriterion("YN_JNL <=", value, "YN_JNL");
            return (Criteria) this;
        }

        public Criteria andYN_JNLLike(String value) {
            addCriterion("YN_JNL like", value, "YN_JNL");
            return (Criteria) this;
        }

        public Criteria andYN_JNLNotLike(String value) {
            addCriterion("YN_JNL not like", value, "YN_JNL");
            return (Criteria) this;
        }

        public Criteria andYN_JNLIn(List<String> values) {
            addCriterion("YN_JNL in", values, "YN_JNL");
            return (Criteria) this;
        }

        public Criteria andYN_JNLNotIn(List<String> values) {
            addCriterion("YN_JNL not in", values, "YN_JNL");
            return (Criteria) this;
        }

        public Criteria andYN_JNLBetween(String value1, String value2) {
            addCriterion("YN_JNL between", value1, value2, "YN_JNL");
            return (Criteria) this;
        }

        public Criteria andYN_JNLNotBetween(String value1, String value2) {
            addCriterion("YN_JNL not between", value1, value2, "YN_JNL");
            return (Criteria) this;
        }

        public Criteria andREG_IDIsNull() {
            addCriterion("REG_ID is null");
            return (Criteria) this;
        }

        public Criteria andREG_IDIsNotNull() {
            addCriterion("REG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andREG_IDEqualTo(String value) {
            addCriterion("REG_ID =", value, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDNotEqualTo(String value) {
            addCriterion("REG_ID <>", value, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDGreaterThan(String value) {
            addCriterion("REG_ID >", value, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDGreaterThanOrEqualTo(String value) {
            addCriterion("REG_ID >=", value, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDLessThan(String value) {
            addCriterion("REG_ID <", value, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDLessThanOrEqualTo(String value) {
            addCriterion("REG_ID <=", value, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDLike(String value) {
            addCriterion("REG_ID like", value, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDNotLike(String value) {
            addCriterion("REG_ID not like", value, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDIn(List<String> values) {
            addCriterion("REG_ID in", values, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDNotIn(List<String> values) {
            addCriterion("REG_ID not in", values, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDBetween(String value1, String value2) {
            addCriterion("REG_ID between", value1, value2, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDNotBetween(String value1, String value2) {
            addCriterion("REG_ID not between", value1, value2, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andYN_FREEIsNull() {
            addCriterion("YN_FREE is null");
            return (Criteria) this;
        }

        public Criteria andYN_FREEIsNotNull() {
            addCriterion("YN_FREE is not null");
            return (Criteria) this;
        }

        public Criteria andYN_FREEEqualTo(String value) {
            addCriterion("YN_FREE =", value, "YN_FREE");
            return (Criteria) this;
        }

        public Criteria andYN_FREENotEqualTo(String value) {
            addCriterion("YN_FREE <>", value, "YN_FREE");
            return (Criteria) this;
        }

        public Criteria andYN_FREEGreaterThan(String value) {
            addCriterion("YN_FREE >", value, "YN_FREE");
            return (Criteria) this;
        }

        public Criteria andYN_FREEGreaterThanOrEqualTo(String value) {
            addCriterion("YN_FREE >=", value, "YN_FREE");
            return (Criteria) this;
        }

        public Criteria andYN_FREELessThan(String value) {
            addCriterion("YN_FREE <", value, "YN_FREE");
            return (Criteria) this;
        }

        public Criteria andYN_FREELessThanOrEqualTo(String value) {
            addCriterion("YN_FREE <=", value, "YN_FREE");
            return (Criteria) this;
        }

        public Criteria andYN_FREELike(String value) {
            addCriterion("YN_FREE like", value, "YN_FREE");
            return (Criteria) this;
        }

        public Criteria andYN_FREENotLike(String value) {
            addCriterion("YN_FREE not like", value, "YN_FREE");
            return (Criteria) this;
        }

        public Criteria andYN_FREEIn(List<String> values) {
            addCriterion("YN_FREE in", values, "YN_FREE");
            return (Criteria) this;
        }

        public Criteria andYN_FREENotIn(List<String> values) {
            addCriterion("YN_FREE not in", values, "YN_FREE");
            return (Criteria) this;
        }

        public Criteria andYN_FREEBetween(String value1, String value2) {
            addCriterion("YN_FREE between", value1, value2, "YN_FREE");
            return (Criteria) this;
        }

        public Criteria andYN_FREENotBetween(String value1, String value2) {
            addCriterion("YN_FREE not between", value1, value2, "YN_FREE");
            return (Criteria) this;
        }

        public Criteria andCD_CHANNELIsNull() {
            addCriterion("CD_CHANNEL is null");
            return (Criteria) this;
        }

        public Criteria andCD_CHANNELIsNotNull() {
            addCriterion("CD_CHANNEL is not null");
            return (Criteria) this;
        }

        public Criteria andCD_CHANNELEqualTo(String value) {
            addCriterion("CD_CHANNEL =", value, "CD_CHANNEL");
            return (Criteria) this;
        }

        public Criteria andCD_CHANNELNotEqualTo(String value) {
            addCriterion("CD_CHANNEL <>", value, "CD_CHANNEL");
            return (Criteria) this;
        }

        public Criteria andCD_CHANNELGreaterThan(String value) {
            addCriterion("CD_CHANNEL >", value, "CD_CHANNEL");
            return (Criteria) this;
        }

        public Criteria andCD_CHANNELGreaterThanOrEqualTo(String value) {
            addCriterion("CD_CHANNEL >=", value, "CD_CHANNEL");
            return (Criteria) this;
        }

        public Criteria andCD_CHANNELLessThan(String value) {
            addCriterion("CD_CHANNEL <", value, "CD_CHANNEL");
            return (Criteria) this;
        }

        public Criteria andCD_CHANNELLessThanOrEqualTo(String value) {
            addCriterion("CD_CHANNEL <=", value, "CD_CHANNEL");
            return (Criteria) this;
        }

        public Criteria andCD_CHANNELLike(String value) {
            addCriterion("CD_CHANNEL like", value, "CD_CHANNEL");
            return (Criteria) this;
        }

        public Criteria andCD_CHANNELNotLike(String value) {
            addCriterion("CD_CHANNEL not like", value, "CD_CHANNEL");
            return (Criteria) this;
        }

        public Criteria andCD_CHANNELIn(List<String> values) {
            addCriterion("CD_CHANNEL in", values, "CD_CHANNEL");
            return (Criteria) this;
        }

        public Criteria andCD_CHANNELNotIn(List<String> values) {
            addCriterion("CD_CHANNEL not in", values, "CD_CHANNEL");
            return (Criteria) this;
        }

        public Criteria andCD_CHANNELBetween(String value1, String value2) {
            addCriterion("CD_CHANNEL between", value1, value2, "CD_CHANNEL");
            return (Criteria) this;
        }

        public Criteria andCD_CHANNELNotBetween(String value1, String value2) {
            addCriterion("CD_CHANNEL not between", value1, value2, "CD_CHANNEL");
            return (Criteria) this;
        }

        public Criteria andJOIN_PATHIsNull() {
            addCriterion("JOIN_PATH is null");
            return (Criteria) this;
        }

        public Criteria andJOIN_PATHIsNotNull() {
            addCriterion("JOIN_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andJOIN_PATHEqualTo(String value) {
            addCriterion("JOIN_PATH =", value, "JOIN_PATH");
            return (Criteria) this;
        }

        public Criteria andJOIN_PATHNotEqualTo(String value) {
            addCriterion("JOIN_PATH <>", value, "JOIN_PATH");
            return (Criteria) this;
        }

        public Criteria andJOIN_PATHGreaterThan(String value) {
            addCriterion("JOIN_PATH >", value, "JOIN_PATH");
            return (Criteria) this;
        }

        public Criteria andJOIN_PATHGreaterThanOrEqualTo(String value) {
            addCriterion("JOIN_PATH >=", value, "JOIN_PATH");
            return (Criteria) this;
        }

        public Criteria andJOIN_PATHLessThan(String value) {
            addCriterion("JOIN_PATH <", value, "JOIN_PATH");
            return (Criteria) this;
        }

        public Criteria andJOIN_PATHLessThanOrEqualTo(String value) {
            addCriterion("JOIN_PATH <=", value, "JOIN_PATH");
            return (Criteria) this;
        }

        public Criteria andJOIN_PATHLike(String value) {
            addCriterion("JOIN_PATH like", value, "JOIN_PATH");
            return (Criteria) this;
        }

        public Criteria andJOIN_PATHNotLike(String value) {
            addCriterion("JOIN_PATH not like", value, "JOIN_PATH");
            return (Criteria) this;
        }

        public Criteria andJOIN_PATHIn(List<String> values) {
            addCriterion("JOIN_PATH in", values, "JOIN_PATH");
            return (Criteria) this;
        }

        public Criteria andJOIN_PATHNotIn(List<String> values) {
            addCriterion("JOIN_PATH not in", values, "JOIN_PATH");
            return (Criteria) this;
        }

        public Criteria andJOIN_PATHBetween(String value1, String value2) {
            addCriterion("JOIN_PATH between", value1, value2, "JOIN_PATH");
            return (Criteria) this;
        }

        public Criteria andJOIN_PATHNotBetween(String value1, String value2) {
            addCriterion("JOIN_PATH not between", value1, value2, "JOIN_PATH");
            return (Criteria) this;
        }

        public Criteria andJOIN_OPTIsNull() {
            addCriterion("JOIN_OPT is null");
            return (Criteria) this;
        }

        public Criteria andJOIN_OPTIsNotNull() {
            addCriterion("JOIN_OPT is not null");
            return (Criteria) this;
        }

        public Criteria andJOIN_OPTEqualTo(String value) {
            addCriterion("JOIN_OPT =", value, "JOIN_OPT");
            return (Criteria) this;
        }

        public Criteria andJOIN_OPTNotEqualTo(String value) {
            addCriterion("JOIN_OPT <>", value, "JOIN_OPT");
            return (Criteria) this;
        }

        public Criteria andJOIN_OPTGreaterThan(String value) {
            addCriterion("JOIN_OPT >", value, "JOIN_OPT");
            return (Criteria) this;
        }

        public Criteria andJOIN_OPTGreaterThanOrEqualTo(String value) {
            addCriterion("JOIN_OPT >=", value, "JOIN_OPT");
            return (Criteria) this;
        }

        public Criteria andJOIN_OPTLessThan(String value) {
            addCriterion("JOIN_OPT <", value, "JOIN_OPT");
            return (Criteria) this;
        }

        public Criteria andJOIN_OPTLessThanOrEqualTo(String value) {
            addCriterion("JOIN_OPT <=", value, "JOIN_OPT");
            return (Criteria) this;
        }

        public Criteria andJOIN_OPTLike(String value) {
            addCriterion("JOIN_OPT like", value, "JOIN_OPT");
            return (Criteria) this;
        }

        public Criteria andJOIN_OPTNotLike(String value) {
            addCriterion("JOIN_OPT not like", value, "JOIN_OPT");
            return (Criteria) this;
        }

        public Criteria andJOIN_OPTIn(List<String> values) {
            addCriterion("JOIN_OPT in", values, "JOIN_OPT");
            return (Criteria) this;
        }

        public Criteria andJOIN_OPTNotIn(List<String> values) {
            addCriterion("JOIN_OPT not in", values, "JOIN_OPT");
            return (Criteria) this;
        }

        public Criteria andJOIN_OPTBetween(String value1, String value2) {
            addCriterion("JOIN_OPT between", value1, value2, "JOIN_OPT");
            return (Criteria) this;
        }

        public Criteria andJOIN_OPTNotBetween(String value1, String value2) {
            addCriterion("JOIN_OPT not between", value1, value2, "JOIN_OPT");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CUST
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 24 11:42:50 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}