package com.duzon.ssh.model;

public class TbCust {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.NO_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String NO_CUST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.NO_ID
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String NO_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.YN_NONPF
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String YN_NONPF;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.NM_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String NM_CUST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.NM_CEO
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String NM_CEO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.CD_ZIP
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String CD_ZIP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.ADDR1
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String ADDR1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.ADDR2
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String ADDR2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.BIZ_STATUS
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String BIZ_STATUS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.BIZ_TYPE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String BIZ_TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.TEL1
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String TEL1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.TEL2
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String TEL2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.TEL3
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String TEL3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.FAX1
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String FAX1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.FAX2
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String FAX2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.FAX3
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String FAX3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.NO_ACCT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String NO_ACCT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.FG_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String FG_CUST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.FG_PAY
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String FG_PAY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.UPDATE_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String UPDATE_USER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.DT_UPDATE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String DT_UPDATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.DT_ENTER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String DT_ENTER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.YN_CSMT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String YN_CSMT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.CD_ERP
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String CD_ERP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.YN_DEL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String YN_DEL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.YN_JNL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String YN_JNL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.REG_ID
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String REG_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.YN_FREE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String YN_FREE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.CD_CHANNEL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String CD_CHANNEL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.JOIN_PATH
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String JOIN_PATH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CUST.JOIN_OPT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String JOIN_OPT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.NO_CUST
     *
     * @return the value of TB_CUST.NO_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getNO_CUST() {
        return NO_CUST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.NO_CUST
     *
     * @param NO_CUST the value for TB_CUST.NO_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setNO_CUST(String NO_CUST) {
        this.NO_CUST = NO_CUST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.NO_ID
     *
     * @return the value of TB_CUST.NO_ID
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getNO_ID() {
        return NO_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.NO_ID
     *
     * @param NO_ID the value for TB_CUST.NO_ID
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setNO_ID(String NO_ID) {
        this.NO_ID = NO_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.YN_NONPF
     *
     * @return the value of TB_CUST.YN_NONPF
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getYN_NONPF() {
        return YN_NONPF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.YN_NONPF
     *
     * @param YN_NONPF the value for TB_CUST.YN_NONPF
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setYN_NONPF(String YN_NONPF) {
        this.YN_NONPF = YN_NONPF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.NM_CUST
     *
     * @return the value of TB_CUST.NM_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getNM_CUST() {
        return NM_CUST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.NM_CUST
     *
     * @param NM_CUST the value for TB_CUST.NM_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setNM_CUST(String NM_CUST) {
        this.NM_CUST = NM_CUST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.NM_CEO
     *
     * @return the value of TB_CUST.NM_CEO
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getNM_CEO() {
        return NM_CEO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.NM_CEO
     *
     * @param NM_CEO the value for TB_CUST.NM_CEO
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setNM_CEO(String NM_CEO) {
        this.NM_CEO = NM_CEO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.CD_ZIP
     *
     * @return the value of TB_CUST.CD_ZIP
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getCD_ZIP() {
        return CD_ZIP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.CD_ZIP
     *
     * @param CD_ZIP the value for TB_CUST.CD_ZIP
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setCD_ZIP(String CD_ZIP) {
        this.CD_ZIP = CD_ZIP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.ADDR1
     *
     * @return the value of TB_CUST.ADDR1
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getADDR1() {
        return ADDR1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.ADDR1
     *
     * @param ADDR1 the value for TB_CUST.ADDR1
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setADDR1(String ADDR1) {
        this.ADDR1 = ADDR1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.ADDR2
     *
     * @return the value of TB_CUST.ADDR2
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getADDR2() {
        return ADDR2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.ADDR2
     *
     * @param ADDR2 the value for TB_CUST.ADDR2
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setADDR2(String ADDR2) {
        this.ADDR2 = ADDR2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.BIZ_STATUS
     *
     * @return the value of TB_CUST.BIZ_STATUS
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getBIZ_STATUS() {
        return BIZ_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.BIZ_STATUS
     *
     * @param BIZ_STATUS the value for TB_CUST.BIZ_STATUS
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setBIZ_STATUS(String BIZ_STATUS) {
        this.BIZ_STATUS = BIZ_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.BIZ_TYPE
     *
     * @return the value of TB_CUST.BIZ_TYPE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getBIZ_TYPE() {
        return BIZ_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.BIZ_TYPE
     *
     * @param BIZ_TYPE the value for TB_CUST.BIZ_TYPE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setBIZ_TYPE(String BIZ_TYPE) {
        this.BIZ_TYPE = BIZ_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.TEL1
     *
     * @return the value of TB_CUST.TEL1
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getTEL1() {
        return TEL1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.TEL1
     *
     * @param TEL1 the value for TB_CUST.TEL1
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setTEL1(String TEL1) {
        this.TEL1 = TEL1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.TEL2
     *
     * @return the value of TB_CUST.TEL2
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getTEL2() {
        return TEL2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.TEL2
     *
     * @param TEL2 the value for TB_CUST.TEL2
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setTEL2(String TEL2) {
        this.TEL2 = TEL2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.TEL3
     *
     * @return the value of TB_CUST.TEL3
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getTEL3() {
        return TEL3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.TEL3
     *
     * @param TEL3 the value for TB_CUST.TEL3
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setTEL3(String TEL3) {
        this.TEL3 = TEL3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.FAX1
     *
     * @return the value of TB_CUST.FAX1
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getFAX1() {
        return FAX1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.FAX1
     *
     * @param FAX1 the value for TB_CUST.FAX1
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setFAX1(String FAX1) {
        this.FAX1 = FAX1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.FAX2
     *
     * @return the value of TB_CUST.FAX2
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getFAX2() {
        return FAX2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.FAX2
     *
     * @param FAX2 the value for TB_CUST.FAX2
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setFAX2(String FAX2) {
        this.FAX2 = FAX2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.FAX3
     *
     * @return the value of TB_CUST.FAX3
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getFAX3() {
        return FAX3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.FAX3
     *
     * @param FAX3 the value for TB_CUST.FAX3
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setFAX3(String FAX3) {
        this.FAX3 = FAX3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.NO_ACCT
     *
     * @return the value of TB_CUST.NO_ACCT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getNO_ACCT() {
        return NO_ACCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.NO_ACCT
     *
     * @param NO_ACCT the value for TB_CUST.NO_ACCT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setNO_ACCT(String NO_ACCT) {
        this.NO_ACCT = NO_ACCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.FG_CUST
     *
     * @return the value of TB_CUST.FG_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getFG_CUST() {
        return FG_CUST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.FG_CUST
     *
     * @param FG_CUST the value for TB_CUST.FG_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setFG_CUST(String FG_CUST) {
        this.FG_CUST = FG_CUST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.FG_PAY
     *
     * @return the value of TB_CUST.FG_PAY
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getFG_PAY() {
        return FG_PAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.FG_PAY
     *
     * @param FG_PAY the value for TB_CUST.FG_PAY
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setFG_PAY(String FG_PAY) {
        this.FG_PAY = FG_PAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.UPDATE_USER
     *
     * @return the value of TB_CUST.UPDATE_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getUPDATE_USER() {
        return UPDATE_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.UPDATE_USER
     *
     * @param UPDATE_USER the value for TB_CUST.UPDATE_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setUPDATE_USER(String UPDATE_USER) {
        this.UPDATE_USER = UPDATE_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.DT_UPDATE
     *
     * @return the value of TB_CUST.DT_UPDATE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getDT_UPDATE() {
        return DT_UPDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.DT_UPDATE
     *
     * @param DT_UPDATE the value for TB_CUST.DT_UPDATE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setDT_UPDATE(String DT_UPDATE) {
        this.DT_UPDATE = DT_UPDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.DT_ENTER
     *
     * @return the value of TB_CUST.DT_ENTER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getDT_ENTER() {
        return DT_ENTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.DT_ENTER
     *
     * @param DT_ENTER the value for TB_CUST.DT_ENTER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setDT_ENTER(String DT_ENTER) {
        this.DT_ENTER = DT_ENTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.YN_CSMT
     *
     * @return the value of TB_CUST.YN_CSMT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getYN_CSMT() {
        return YN_CSMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.YN_CSMT
     *
     * @param YN_CSMT the value for TB_CUST.YN_CSMT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setYN_CSMT(String YN_CSMT) {
        this.YN_CSMT = YN_CSMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.CD_ERP
     *
     * @return the value of TB_CUST.CD_ERP
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getCD_ERP() {
        return CD_ERP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.CD_ERP
     *
     * @param CD_ERP the value for TB_CUST.CD_ERP
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setCD_ERP(String CD_ERP) {
        this.CD_ERP = CD_ERP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.YN_DEL
     *
     * @return the value of TB_CUST.YN_DEL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getYN_DEL() {
        return YN_DEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.YN_DEL
     *
     * @param YN_DEL the value for TB_CUST.YN_DEL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setYN_DEL(String YN_DEL) {
        this.YN_DEL = YN_DEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.YN_JNL
     *
     * @return the value of TB_CUST.YN_JNL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getYN_JNL() {
        return YN_JNL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.YN_JNL
     *
     * @param YN_JNL the value for TB_CUST.YN_JNL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setYN_JNL(String YN_JNL) {
        this.YN_JNL = YN_JNL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.REG_ID
     *
     * @return the value of TB_CUST.REG_ID
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getREG_ID() {
        return REG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.REG_ID
     *
     * @param REG_ID the value for TB_CUST.REG_ID
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setREG_ID(String REG_ID) {
        this.REG_ID = REG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.YN_FREE
     *
     * @return the value of TB_CUST.YN_FREE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getYN_FREE() {
        return YN_FREE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.YN_FREE
     *
     * @param YN_FREE the value for TB_CUST.YN_FREE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setYN_FREE(String YN_FREE) {
        this.YN_FREE = YN_FREE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.CD_CHANNEL
     *
     * @return the value of TB_CUST.CD_CHANNEL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getCD_CHANNEL() {
        return CD_CHANNEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.CD_CHANNEL
     *
     * @param CD_CHANNEL the value for TB_CUST.CD_CHANNEL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setCD_CHANNEL(String CD_CHANNEL) {
        this.CD_CHANNEL = CD_CHANNEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.JOIN_PATH
     *
     * @return the value of TB_CUST.JOIN_PATH
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getJOIN_PATH() {
        return JOIN_PATH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.JOIN_PATH
     *
     * @param JOIN_PATH the value for TB_CUST.JOIN_PATH
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setJOIN_PATH(String JOIN_PATH) {
        this.JOIN_PATH = JOIN_PATH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CUST.JOIN_OPT
     *
     * @return the value of TB_CUST.JOIN_OPT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getJOIN_OPT() {
        return JOIN_OPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CUST.JOIN_OPT
     *
     * @param JOIN_OPT the value for TB_CUST.JOIN_OPT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setJOIN_OPT(String JOIN_OPT) {
        this.JOIN_OPT = JOIN_OPT;
    }
}