package com.duzon.ssh.model;

public class TbUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.NO_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String NO_USER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.NO_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String NO_CUST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.ID
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.PASSWD
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String PASSWD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.YN_CEO
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String YN_CEO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.NM_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String NM_USER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.EMAIL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String EMAIL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.MOBILE1
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String MOBILE1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.MOBILE2
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String MOBILE2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.MOBILE3
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String MOBILE3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.NM_DEPT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String NM_DEPT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.YN_MAIL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String YN_MAIL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.YN_SMS
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String YN_SMS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.UPPER_NO_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String UPPER_NO_USER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.DT_ENTER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String DT_ENTER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.DT_UPDATE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String DT_UPDATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.ENTER_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String ENTER_USER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.UPDATE_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String UPDATE_USER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.STAT_MAIL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String STAT_MAIL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.NO_ACCT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String NO_ACCT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.YN_DEL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String YN_DEL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.TEL1
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String TEL1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.TEL2
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String TEL2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.TEL3
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String TEL3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.REG_ID
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String REG_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.CD_GRADE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String CD_GRADE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.YN_VISUAL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String YN_VISUAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.CNT_PW_ERROR
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private Short CNT_PW_ERROR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.YN_PW_ADMIN_INIT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String YN_PW_ADMIN_INIT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.DT_PW_ADMIN_INIT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String DT_PW_ADMIN_INIT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.DT_PW_UPDATE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String DT_PW_UPDATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USER.DT_PW_NEXT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    private String DT_PW_NEXT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.NO_USER
     *
     * @return the value of TB_USER.NO_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getNO_USER() {
        return NO_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.NO_USER
     *
     * @param NO_USER the value for TB_USER.NO_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setNO_USER(String NO_USER) {
        this.NO_USER = NO_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.NO_CUST
     *
     * @return the value of TB_USER.NO_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getNO_CUST() {
        return NO_CUST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.NO_CUST
     *
     * @param NO_CUST the value for TB_USER.NO_CUST
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setNO_CUST(String NO_CUST) {
        this.NO_CUST = NO_CUST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.ID
     *
     * @return the value of TB_USER.ID
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.ID
     *
     * @param ID the value for TB_USER.ID
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setID(String ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.PASSWD
     *
     * @return the value of TB_USER.PASSWD
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getPASSWD() {
        return PASSWD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.PASSWD
     *
     * @param PASSWD the value for TB_USER.PASSWD
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setPASSWD(String PASSWD) {
        this.PASSWD = PASSWD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.YN_CEO
     *
     * @return the value of TB_USER.YN_CEO
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getYN_CEO() {
        return YN_CEO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.YN_CEO
     *
     * @param YN_CEO the value for TB_USER.YN_CEO
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setYN_CEO(String YN_CEO) {
        this.YN_CEO = YN_CEO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.NM_USER
     *
     * @return the value of TB_USER.NM_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getNM_USER() {
        return NM_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.NM_USER
     *
     * @param NM_USER the value for TB_USER.NM_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setNM_USER(String NM_USER) {
        this.NM_USER = NM_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.EMAIL
     *
     * @return the value of TB_USER.EMAIL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getEMAIL() {
        return EMAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.EMAIL
     *
     * @param EMAIL the value for TB_USER.EMAIL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setEMAIL(String EMAIL) {
        this.EMAIL = EMAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.MOBILE1
     *
     * @return the value of TB_USER.MOBILE1
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getMOBILE1() {
        return MOBILE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.MOBILE1
     *
     * @param MOBILE1 the value for TB_USER.MOBILE1
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setMOBILE1(String MOBILE1) {
        this.MOBILE1 = MOBILE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.MOBILE2
     *
     * @return the value of TB_USER.MOBILE2
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getMOBILE2() {
        return MOBILE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.MOBILE2
     *
     * @param MOBILE2 the value for TB_USER.MOBILE2
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setMOBILE2(String MOBILE2) {
        this.MOBILE2 = MOBILE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.MOBILE3
     *
     * @return the value of TB_USER.MOBILE3
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getMOBILE3() {
        return MOBILE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.MOBILE3
     *
     * @param MOBILE3 the value for TB_USER.MOBILE3
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setMOBILE3(String MOBILE3) {
        this.MOBILE3 = MOBILE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.NM_DEPT
     *
     * @return the value of TB_USER.NM_DEPT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getNM_DEPT() {
        return NM_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.NM_DEPT
     *
     * @param NM_DEPT the value for TB_USER.NM_DEPT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setNM_DEPT(String NM_DEPT) {
        this.NM_DEPT = NM_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.YN_MAIL
     *
     * @return the value of TB_USER.YN_MAIL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getYN_MAIL() {
        return YN_MAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.YN_MAIL
     *
     * @param YN_MAIL the value for TB_USER.YN_MAIL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setYN_MAIL(String YN_MAIL) {
        this.YN_MAIL = YN_MAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.YN_SMS
     *
     * @return the value of TB_USER.YN_SMS
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getYN_SMS() {
        return YN_SMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.YN_SMS
     *
     * @param YN_SMS the value for TB_USER.YN_SMS
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setYN_SMS(String YN_SMS) {
        this.YN_SMS = YN_SMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.UPPER_NO_USER
     *
     * @return the value of TB_USER.UPPER_NO_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getUPPER_NO_USER() {
        return UPPER_NO_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.UPPER_NO_USER
     *
     * @param UPPER_NO_USER the value for TB_USER.UPPER_NO_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setUPPER_NO_USER(String UPPER_NO_USER) {
        this.UPPER_NO_USER = UPPER_NO_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.DT_ENTER
     *
     * @return the value of TB_USER.DT_ENTER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getDT_ENTER() {
        return DT_ENTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.DT_ENTER
     *
     * @param DT_ENTER the value for TB_USER.DT_ENTER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setDT_ENTER(String DT_ENTER) {
        this.DT_ENTER = DT_ENTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.DT_UPDATE
     *
     * @return the value of TB_USER.DT_UPDATE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getDT_UPDATE() {
        return DT_UPDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.DT_UPDATE
     *
     * @param DT_UPDATE the value for TB_USER.DT_UPDATE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setDT_UPDATE(String DT_UPDATE) {
        this.DT_UPDATE = DT_UPDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.ENTER_USER
     *
     * @return the value of TB_USER.ENTER_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getENTER_USER() {
        return ENTER_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.ENTER_USER
     *
     * @param ENTER_USER the value for TB_USER.ENTER_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setENTER_USER(String ENTER_USER) {
        this.ENTER_USER = ENTER_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.UPDATE_USER
     *
     * @return the value of TB_USER.UPDATE_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getUPDATE_USER() {
        return UPDATE_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.UPDATE_USER
     *
     * @param UPDATE_USER the value for TB_USER.UPDATE_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setUPDATE_USER(String UPDATE_USER) {
        this.UPDATE_USER = UPDATE_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.STAT_MAIL
     *
     * @return the value of TB_USER.STAT_MAIL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getSTAT_MAIL() {
        return STAT_MAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.STAT_MAIL
     *
     * @param STAT_MAIL the value for TB_USER.STAT_MAIL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setSTAT_MAIL(String STAT_MAIL) {
        this.STAT_MAIL = STAT_MAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.NO_ACCT
     *
     * @return the value of TB_USER.NO_ACCT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getNO_ACCT() {
        return NO_ACCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.NO_ACCT
     *
     * @param NO_ACCT the value for TB_USER.NO_ACCT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setNO_ACCT(String NO_ACCT) {
        this.NO_ACCT = NO_ACCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.YN_DEL
     *
     * @return the value of TB_USER.YN_DEL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getYN_DEL() {
        return YN_DEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.YN_DEL
     *
     * @param YN_DEL the value for TB_USER.YN_DEL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setYN_DEL(String YN_DEL) {
        this.YN_DEL = YN_DEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.TEL1
     *
     * @return the value of TB_USER.TEL1
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getTEL1() {
        return TEL1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.TEL1
     *
     * @param TEL1 the value for TB_USER.TEL1
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setTEL1(String TEL1) {
        this.TEL1 = TEL1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.TEL2
     *
     * @return the value of TB_USER.TEL2
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getTEL2() {
        return TEL2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.TEL2
     *
     * @param TEL2 the value for TB_USER.TEL2
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setTEL2(String TEL2) {
        this.TEL2 = TEL2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.TEL3
     *
     * @return the value of TB_USER.TEL3
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getTEL3() {
        return TEL3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.TEL3
     *
     * @param TEL3 the value for TB_USER.TEL3
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setTEL3(String TEL3) {
        this.TEL3 = TEL3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.REG_ID
     *
     * @return the value of TB_USER.REG_ID
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getREG_ID() {
        return REG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.REG_ID
     *
     * @param REG_ID the value for TB_USER.REG_ID
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setREG_ID(String REG_ID) {
        this.REG_ID = REG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.CD_GRADE
     *
     * @return the value of TB_USER.CD_GRADE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getCD_GRADE() {
        return CD_GRADE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.CD_GRADE
     *
     * @param CD_GRADE the value for TB_USER.CD_GRADE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setCD_GRADE(String CD_GRADE) {
        this.CD_GRADE = CD_GRADE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.YN_VISUAL
     *
     * @return the value of TB_USER.YN_VISUAL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getYN_VISUAL() {
        return YN_VISUAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.YN_VISUAL
     *
     * @param YN_VISUAL the value for TB_USER.YN_VISUAL
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setYN_VISUAL(String YN_VISUAL) {
        this.YN_VISUAL = YN_VISUAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.CNT_PW_ERROR
     *
     * @return the value of TB_USER.CNT_PW_ERROR
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public Short getCNT_PW_ERROR() {
        return CNT_PW_ERROR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.CNT_PW_ERROR
     *
     * @param CNT_PW_ERROR the value for TB_USER.CNT_PW_ERROR
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setCNT_PW_ERROR(Short CNT_PW_ERROR) {
        this.CNT_PW_ERROR = CNT_PW_ERROR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.YN_PW_ADMIN_INIT
     *
     * @return the value of TB_USER.YN_PW_ADMIN_INIT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getYN_PW_ADMIN_INIT() {
        return YN_PW_ADMIN_INIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.YN_PW_ADMIN_INIT
     *
     * @param YN_PW_ADMIN_INIT the value for TB_USER.YN_PW_ADMIN_INIT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setYN_PW_ADMIN_INIT(String YN_PW_ADMIN_INIT) {
        this.YN_PW_ADMIN_INIT = YN_PW_ADMIN_INIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.DT_PW_ADMIN_INIT
     *
     * @return the value of TB_USER.DT_PW_ADMIN_INIT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getDT_PW_ADMIN_INIT() {
        return DT_PW_ADMIN_INIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.DT_PW_ADMIN_INIT
     *
     * @param DT_PW_ADMIN_INIT the value for TB_USER.DT_PW_ADMIN_INIT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setDT_PW_ADMIN_INIT(String DT_PW_ADMIN_INIT) {
        this.DT_PW_ADMIN_INIT = DT_PW_ADMIN_INIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.DT_PW_UPDATE
     *
     * @return the value of TB_USER.DT_PW_UPDATE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getDT_PW_UPDATE() {
        return DT_PW_UPDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.DT_PW_UPDATE
     *
     * @param DT_PW_UPDATE the value for TB_USER.DT_PW_UPDATE
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setDT_PW_UPDATE(String DT_PW_UPDATE) {
        this.DT_PW_UPDATE = DT_PW_UPDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USER.DT_PW_NEXT
     *
     * @return the value of TB_USER.DT_PW_NEXT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getDT_PW_NEXT() {
        return DT_PW_NEXT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USER.DT_PW_NEXT
     *
     * @param DT_PW_NEXT the value for TB_USER.DT_PW_NEXT
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setDT_PW_NEXT(String DT_PW_NEXT) {
        this.DT_PW_NEXT = DT_PW_NEXT;
    }
}