package com.duzon.ssh.model;

import java.util.ArrayList;
import java.util.List;

public class TbUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public TbUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNO_USERIsNull() {
            addCriterion("NO_USER is null");
            return (Criteria) this;
        }

        public Criteria andNO_USERIsNotNull() {
            addCriterion("NO_USER is not null");
            return (Criteria) this;
        }

        public Criteria andNO_USEREqualTo(String value) {
            addCriterion("NO_USER =", value, "NO_USER");
            return (Criteria) this;
        }

        public Criteria andNO_USERNotEqualTo(String value) {
            addCriterion("NO_USER <>", value, "NO_USER");
            return (Criteria) this;
        }

        public Criteria andNO_USERGreaterThan(String value) {
            addCriterion("NO_USER >", value, "NO_USER");
            return (Criteria) this;
        }

        public Criteria andNO_USERGreaterThanOrEqualTo(String value) {
            addCriterion("NO_USER >=", value, "NO_USER");
            return (Criteria) this;
        }

        public Criteria andNO_USERLessThan(String value) {
            addCriterion("NO_USER <", value, "NO_USER");
            return (Criteria) this;
        }

        public Criteria andNO_USERLessThanOrEqualTo(String value) {
            addCriterion("NO_USER <=", value, "NO_USER");
            return (Criteria) this;
        }

        public Criteria andNO_USERLike(String value) {
            addCriterion("NO_USER like", value, "NO_USER");
            return (Criteria) this;
        }

        public Criteria andNO_USERNotLike(String value) {
            addCriterion("NO_USER not like", value, "NO_USER");
            return (Criteria) this;
        }

        public Criteria andNO_USERIn(List<String> values) {
            addCriterion("NO_USER in", values, "NO_USER");
            return (Criteria) this;
        }

        public Criteria andNO_USERNotIn(List<String> values) {
            addCriterion("NO_USER not in", values, "NO_USER");
            return (Criteria) this;
        }

        public Criteria andNO_USERBetween(String value1, String value2) {
            addCriterion("NO_USER between", value1, value2, "NO_USER");
            return (Criteria) this;
        }

        public Criteria andNO_USERNotBetween(String value1, String value2) {
            addCriterion("NO_USER not between", value1, value2, "NO_USER");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTIsNull() {
            addCriterion("NO_CUST is null");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTIsNotNull() {
            addCriterion("NO_CUST is not null");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTEqualTo(String value) {
            addCriterion("NO_CUST =", value, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTNotEqualTo(String value) {
            addCriterion("NO_CUST <>", value, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTGreaterThan(String value) {
            addCriterion("NO_CUST >", value, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTGreaterThanOrEqualTo(String value) {
            addCriterion("NO_CUST >=", value, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTLessThan(String value) {
            addCriterion("NO_CUST <", value, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTLessThanOrEqualTo(String value) {
            addCriterion("NO_CUST <=", value, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTLike(String value) {
            addCriterion("NO_CUST like", value, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTNotLike(String value) {
            addCriterion("NO_CUST not like", value, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTIn(List<String> values) {
            addCriterion("NO_CUST in", values, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTNotIn(List<String> values) {
            addCriterion("NO_CUST not in", values, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTBetween(String value1, String value2) {
            addCriterion("NO_CUST between", value1, value2, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andNO_CUSTNotBetween(String value1, String value2) {
            addCriterion("NO_CUST not between", value1, value2, "NO_CUST");
            return (Criteria) this;
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(String value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(String value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(String value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(String value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLike(String value) {
            addCriterion("ID like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotLike(String value) {
            addCriterion("ID not like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<String> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<String> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andPASSWDIsNull() {
            addCriterion("PASSWD is null");
            return (Criteria) this;
        }

        public Criteria andPASSWDIsNotNull() {
            addCriterion("PASSWD is not null");
            return (Criteria) this;
        }

        public Criteria andPASSWDEqualTo(String value) {
            addCriterion("PASSWD =", value, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDNotEqualTo(String value) {
            addCriterion("PASSWD <>", value, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDGreaterThan(String value) {
            addCriterion("PASSWD >", value, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWD >=", value, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDLessThan(String value) {
            addCriterion("PASSWD <", value, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDLessThanOrEqualTo(String value) {
            addCriterion("PASSWD <=", value, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDLike(String value) {
            addCriterion("PASSWD like", value, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDNotLike(String value) {
            addCriterion("PASSWD not like", value, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDIn(List<String> values) {
            addCriterion("PASSWD in", values, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDNotIn(List<String> values) {
            addCriterion("PASSWD not in", values, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDBetween(String value1, String value2) {
            addCriterion("PASSWD between", value1, value2, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDNotBetween(String value1, String value2) {
            addCriterion("PASSWD not between", value1, value2, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andYN_CEOIsNull() {
            addCriterion("YN_CEO is null");
            return (Criteria) this;
        }

        public Criteria andYN_CEOIsNotNull() {
            addCriterion("YN_CEO is not null");
            return (Criteria) this;
        }

        public Criteria andYN_CEOEqualTo(String value) {
            addCriterion("YN_CEO =", value, "YN_CEO");
            return (Criteria) this;
        }

        public Criteria andYN_CEONotEqualTo(String value) {
            addCriterion("YN_CEO <>", value, "YN_CEO");
            return (Criteria) this;
        }

        public Criteria andYN_CEOGreaterThan(String value) {
            addCriterion("YN_CEO >", value, "YN_CEO");
            return (Criteria) this;
        }

        public Criteria andYN_CEOGreaterThanOrEqualTo(String value) {
            addCriterion("YN_CEO >=", value, "YN_CEO");
            return (Criteria) this;
        }

        public Criteria andYN_CEOLessThan(String value) {
            addCriterion("YN_CEO <", value, "YN_CEO");
            return (Criteria) this;
        }

        public Criteria andYN_CEOLessThanOrEqualTo(String value) {
            addCriterion("YN_CEO <=", value, "YN_CEO");
            return (Criteria) this;
        }

        public Criteria andYN_CEOLike(String value) {
            addCriterion("YN_CEO like", value, "YN_CEO");
            return (Criteria) this;
        }

        public Criteria andYN_CEONotLike(String value) {
            addCriterion("YN_CEO not like", value, "YN_CEO");
            return (Criteria) this;
        }

        public Criteria andYN_CEOIn(List<String> values) {
            addCriterion("YN_CEO in", values, "YN_CEO");
            return (Criteria) this;
        }

        public Criteria andYN_CEONotIn(List<String> values) {
            addCriterion("YN_CEO not in", values, "YN_CEO");
            return (Criteria) this;
        }

        public Criteria andYN_CEOBetween(String value1, String value2) {
            addCriterion("YN_CEO between", value1, value2, "YN_CEO");
            return (Criteria) this;
        }

        public Criteria andYN_CEONotBetween(String value1, String value2) {
            addCriterion("YN_CEO not between", value1, value2, "YN_CEO");
            return (Criteria) this;
        }

        public Criteria andNM_USERIsNull() {
            addCriterion("NM_USER is null");
            return (Criteria) this;
        }

        public Criteria andNM_USERIsNotNull() {
            addCriterion("NM_USER is not null");
            return (Criteria) this;
        }

        public Criteria andNM_USEREqualTo(String value) {
            addCriterion("NM_USER =", value, "NM_USER");
            return (Criteria) this;
        }

        public Criteria andNM_USERNotEqualTo(String value) {
            addCriterion("NM_USER <>", value, "NM_USER");
            return (Criteria) this;
        }

        public Criteria andNM_USERGreaterThan(String value) {
            addCriterion("NM_USER >", value, "NM_USER");
            return (Criteria) this;
        }

        public Criteria andNM_USERGreaterThanOrEqualTo(String value) {
            addCriterion("NM_USER >=", value, "NM_USER");
            return (Criteria) this;
        }

        public Criteria andNM_USERLessThan(String value) {
            addCriterion("NM_USER <", value, "NM_USER");
            return (Criteria) this;
        }

        public Criteria andNM_USERLessThanOrEqualTo(String value) {
            addCriterion("NM_USER <=", value, "NM_USER");
            return (Criteria) this;
        }

        public Criteria andNM_USERLike(String value) {
            addCriterion("NM_USER like", value, "NM_USER");
            return (Criteria) this;
        }

        public Criteria andNM_USERNotLike(String value) {
            addCriterion("NM_USER not like", value, "NM_USER");
            return (Criteria) this;
        }

        public Criteria andNM_USERIn(List<String> values) {
            addCriterion("NM_USER in", values, "NM_USER");
            return (Criteria) this;
        }

        public Criteria andNM_USERNotIn(List<String> values) {
            addCriterion("NM_USER not in", values, "NM_USER");
            return (Criteria) this;
        }

        public Criteria andNM_USERBetween(String value1, String value2) {
            addCriterion("NM_USER between", value1, value2, "NM_USER");
            return (Criteria) this;
        }

        public Criteria andNM_USERNotBetween(String value1, String value2) {
            addCriterion("NM_USER not between", value1, value2, "NM_USER");
            return (Criteria) this;
        }

        public Criteria andEMAILIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEMAILIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEMAILEqualTo(String value) {
            addCriterion("EMAIL =", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILGreaterThan(String value) {
            addCriterion("EMAIL >", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILLessThan(String value) {
            addCriterion("EMAIL <", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILLike(String value) {
            addCriterion("EMAIL like", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILNotLike(String value) {
            addCriterion("EMAIL not like", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILIn(List<String> values) {
            addCriterion("EMAIL in", values, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andMOBILE1IsNull() {
            addCriterion("MOBILE1 is null");
            return (Criteria) this;
        }

        public Criteria andMOBILE1IsNotNull() {
            addCriterion("MOBILE1 is not null");
            return (Criteria) this;
        }

        public Criteria andMOBILE1EqualTo(String value) {
            addCriterion("MOBILE1 =", value, "MOBILE1");
            return (Criteria) this;
        }

        public Criteria andMOBILE1NotEqualTo(String value) {
            addCriterion("MOBILE1 <>", value, "MOBILE1");
            return (Criteria) this;
        }

        public Criteria andMOBILE1GreaterThan(String value) {
            addCriterion("MOBILE1 >", value, "MOBILE1");
            return (Criteria) this;
        }

        public Criteria andMOBILE1GreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE1 >=", value, "MOBILE1");
            return (Criteria) this;
        }

        public Criteria andMOBILE1LessThan(String value) {
            addCriterion("MOBILE1 <", value, "MOBILE1");
            return (Criteria) this;
        }

        public Criteria andMOBILE1LessThanOrEqualTo(String value) {
            addCriterion("MOBILE1 <=", value, "MOBILE1");
            return (Criteria) this;
        }

        public Criteria andMOBILE1Like(String value) {
            addCriterion("MOBILE1 like", value, "MOBILE1");
            return (Criteria) this;
        }

        public Criteria andMOBILE1NotLike(String value) {
            addCriterion("MOBILE1 not like", value, "MOBILE1");
            return (Criteria) this;
        }

        public Criteria andMOBILE1In(List<String> values) {
            addCriterion("MOBILE1 in", values, "MOBILE1");
            return (Criteria) this;
        }

        public Criteria andMOBILE1NotIn(List<String> values) {
            addCriterion("MOBILE1 not in", values, "MOBILE1");
            return (Criteria) this;
        }

        public Criteria andMOBILE1Between(String value1, String value2) {
            addCriterion("MOBILE1 between", value1, value2, "MOBILE1");
            return (Criteria) this;
        }

        public Criteria andMOBILE1NotBetween(String value1, String value2) {
            addCriterion("MOBILE1 not between", value1, value2, "MOBILE1");
            return (Criteria) this;
        }

        public Criteria andMOBILE2IsNull() {
            addCriterion("MOBILE2 is null");
            return (Criteria) this;
        }

        public Criteria andMOBILE2IsNotNull() {
            addCriterion("MOBILE2 is not null");
            return (Criteria) this;
        }

        public Criteria andMOBILE2EqualTo(String value) {
            addCriterion("MOBILE2 =", value, "MOBILE2");
            return (Criteria) this;
        }

        public Criteria andMOBILE2NotEqualTo(String value) {
            addCriterion("MOBILE2 <>", value, "MOBILE2");
            return (Criteria) this;
        }

        public Criteria andMOBILE2GreaterThan(String value) {
            addCriterion("MOBILE2 >", value, "MOBILE2");
            return (Criteria) this;
        }

        public Criteria andMOBILE2GreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE2 >=", value, "MOBILE2");
            return (Criteria) this;
        }

        public Criteria andMOBILE2LessThan(String value) {
            addCriterion("MOBILE2 <", value, "MOBILE2");
            return (Criteria) this;
        }

        public Criteria andMOBILE2LessThanOrEqualTo(String value) {
            addCriterion("MOBILE2 <=", value, "MOBILE2");
            return (Criteria) this;
        }

        public Criteria andMOBILE2Like(String value) {
            addCriterion("MOBILE2 like", value, "MOBILE2");
            return (Criteria) this;
        }

        public Criteria andMOBILE2NotLike(String value) {
            addCriterion("MOBILE2 not like", value, "MOBILE2");
            return (Criteria) this;
        }

        public Criteria andMOBILE2In(List<String> values) {
            addCriterion("MOBILE2 in", values, "MOBILE2");
            return (Criteria) this;
        }

        public Criteria andMOBILE2NotIn(List<String> values) {
            addCriterion("MOBILE2 not in", values, "MOBILE2");
            return (Criteria) this;
        }

        public Criteria andMOBILE2Between(String value1, String value2) {
            addCriterion("MOBILE2 between", value1, value2, "MOBILE2");
            return (Criteria) this;
        }

        public Criteria andMOBILE2NotBetween(String value1, String value2) {
            addCriterion("MOBILE2 not between", value1, value2, "MOBILE2");
            return (Criteria) this;
        }

        public Criteria andMOBILE3IsNull() {
            addCriterion("MOBILE3 is null");
            return (Criteria) this;
        }

        public Criteria andMOBILE3IsNotNull() {
            addCriterion("MOBILE3 is not null");
            return (Criteria) this;
        }

        public Criteria andMOBILE3EqualTo(String value) {
            addCriterion("MOBILE3 =", value, "MOBILE3");
            return (Criteria) this;
        }

        public Criteria andMOBILE3NotEqualTo(String value) {
            addCriterion("MOBILE3 <>", value, "MOBILE3");
            return (Criteria) this;
        }

        public Criteria andMOBILE3GreaterThan(String value) {
            addCriterion("MOBILE3 >", value, "MOBILE3");
            return (Criteria) this;
        }

        public Criteria andMOBILE3GreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE3 >=", value, "MOBILE3");
            return (Criteria) this;
        }

        public Criteria andMOBILE3LessThan(String value) {
            addCriterion("MOBILE3 <", value, "MOBILE3");
            return (Criteria) this;
        }

        public Criteria andMOBILE3LessThanOrEqualTo(String value) {
            addCriterion("MOBILE3 <=", value, "MOBILE3");
            return (Criteria) this;
        }

        public Criteria andMOBILE3Like(String value) {
            addCriterion("MOBILE3 like", value, "MOBILE3");
            return (Criteria) this;
        }

        public Criteria andMOBILE3NotLike(String value) {
            addCriterion("MOBILE3 not like", value, "MOBILE3");
            return (Criteria) this;
        }

        public Criteria andMOBILE3In(List<String> values) {
            addCriterion("MOBILE3 in", values, "MOBILE3");
            return (Criteria) this;
        }

        public Criteria andMOBILE3NotIn(List<String> values) {
            addCriterion("MOBILE3 not in", values, "MOBILE3");
            return (Criteria) this;
        }

        public Criteria andMOBILE3Between(String value1, String value2) {
            addCriterion("MOBILE3 between", value1, value2, "MOBILE3");
            return (Criteria) this;
        }

        public Criteria andMOBILE3NotBetween(String value1, String value2) {
            addCriterion("MOBILE3 not between", value1, value2, "MOBILE3");
            return (Criteria) this;
        }

        public Criteria andNM_DEPTIsNull() {
            addCriterion("NM_DEPT is null");
            return (Criteria) this;
        }

        public Criteria andNM_DEPTIsNotNull() {
            addCriterion("NM_DEPT is not null");
            return (Criteria) this;
        }

        public Criteria andNM_DEPTEqualTo(String value) {
            addCriterion("NM_DEPT =", value, "NM_DEPT");
            return (Criteria) this;
        }

        public Criteria andNM_DEPTNotEqualTo(String value) {
            addCriterion("NM_DEPT <>", value, "NM_DEPT");
            return (Criteria) this;
        }

        public Criteria andNM_DEPTGreaterThan(String value) {
            addCriterion("NM_DEPT >", value, "NM_DEPT");
            return (Criteria) this;
        }

        public Criteria andNM_DEPTGreaterThanOrEqualTo(String value) {
            addCriterion("NM_DEPT >=", value, "NM_DEPT");
            return (Criteria) this;
        }

        public Criteria andNM_DEPTLessThan(String value) {
            addCriterion("NM_DEPT <", value, "NM_DEPT");
            return (Criteria) this;
        }

        public Criteria andNM_DEPTLessThanOrEqualTo(String value) {
            addCriterion("NM_DEPT <=", value, "NM_DEPT");
            return (Criteria) this;
        }

        public Criteria andNM_DEPTLike(String value) {
            addCriterion("NM_DEPT like", value, "NM_DEPT");
            return (Criteria) this;
        }

        public Criteria andNM_DEPTNotLike(String value) {
            addCriterion("NM_DEPT not like", value, "NM_DEPT");
            return (Criteria) this;
        }

        public Criteria andNM_DEPTIn(List<String> values) {
            addCriterion("NM_DEPT in", values, "NM_DEPT");
            return (Criteria) this;
        }

        public Criteria andNM_DEPTNotIn(List<String> values) {
            addCriterion("NM_DEPT not in", values, "NM_DEPT");
            return (Criteria) this;
        }

        public Criteria andNM_DEPTBetween(String value1, String value2) {
            addCriterion("NM_DEPT between", value1, value2, "NM_DEPT");
            return (Criteria) this;
        }

        public Criteria andNM_DEPTNotBetween(String value1, String value2) {
            addCriterion("NM_DEPT not between", value1, value2, "NM_DEPT");
            return (Criteria) this;
        }

        public Criteria andYN_MAILIsNull() {
            addCriterion("YN_MAIL is null");
            return (Criteria) this;
        }

        public Criteria andYN_MAILIsNotNull() {
            addCriterion("YN_MAIL is not null");
            return (Criteria) this;
        }

        public Criteria andYN_MAILEqualTo(String value) {
            addCriterion("YN_MAIL =", value, "YN_MAIL");
            return (Criteria) this;
        }

        public Criteria andYN_MAILNotEqualTo(String value) {
            addCriterion("YN_MAIL <>", value, "YN_MAIL");
            return (Criteria) this;
        }

        public Criteria andYN_MAILGreaterThan(String value) {
            addCriterion("YN_MAIL >", value, "YN_MAIL");
            return (Criteria) this;
        }

        public Criteria andYN_MAILGreaterThanOrEqualTo(String value) {
            addCriterion("YN_MAIL >=", value, "YN_MAIL");
            return (Criteria) this;
        }

        public Criteria andYN_MAILLessThan(String value) {
            addCriterion("YN_MAIL <", value, "YN_MAIL");
            return (Criteria) this;
        }

        public Criteria andYN_MAILLessThanOrEqualTo(String value) {
            addCriterion("YN_MAIL <=", value, "YN_MAIL");
            return (Criteria) this;
        }

        public Criteria andYN_MAILLike(String value) {
            addCriterion("YN_MAIL like", value, "YN_MAIL");
            return (Criteria) this;
        }

        public Criteria andYN_MAILNotLike(String value) {
            addCriterion("YN_MAIL not like", value, "YN_MAIL");
            return (Criteria) this;
        }

        public Criteria andYN_MAILIn(List<String> values) {
            addCriterion("YN_MAIL in", values, "YN_MAIL");
            return (Criteria) this;
        }

        public Criteria andYN_MAILNotIn(List<String> values) {
            addCriterion("YN_MAIL not in", values, "YN_MAIL");
            return (Criteria) this;
        }

        public Criteria andYN_MAILBetween(String value1, String value2) {
            addCriterion("YN_MAIL between", value1, value2, "YN_MAIL");
            return (Criteria) this;
        }

        public Criteria andYN_MAILNotBetween(String value1, String value2) {
            addCriterion("YN_MAIL not between", value1, value2, "YN_MAIL");
            return (Criteria) this;
        }

        public Criteria andYN_SMSIsNull() {
            addCriterion("YN_SMS is null");
            return (Criteria) this;
        }

        public Criteria andYN_SMSIsNotNull() {
            addCriterion("YN_SMS is not null");
            return (Criteria) this;
        }

        public Criteria andYN_SMSEqualTo(String value) {
            addCriterion("YN_SMS =", value, "YN_SMS");
            return (Criteria) this;
        }

        public Criteria andYN_SMSNotEqualTo(String value) {
            addCriterion("YN_SMS <>", value, "YN_SMS");
            return (Criteria) this;
        }

        public Criteria andYN_SMSGreaterThan(String value) {
            addCriterion("YN_SMS >", value, "YN_SMS");
            return (Criteria) this;
        }

        public Criteria andYN_SMSGreaterThanOrEqualTo(String value) {
            addCriterion("YN_SMS >=", value, "YN_SMS");
            return (Criteria) this;
        }

        public Criteria andYN_SMSLessThan(String value) {
            addCriterion("YN_SMS <", value, "YN_SMS");
            return (Criteria) this;
        }

        public Criteria andYN_SMSLessThanOrEqualTo(String value) {
            addCriterion("YN_SMS <=", value, "YN_SMS");
            return (Criteria) this;
        }

        public Criteria andYN_SMSLike(String value) {
            addCriterion("YN_SMS like", value, "YN_SMS");
            return (Criteria) this;
        }

        public Criteria andYN_SMSNotLike(String value) {
            addCriterion("YN_SMS not like", value, "YN_SMS");
            return (Criteria) this;
        }

        public Criteria andYN_SMSIn(List<String> values) {
            addCriterion("YN_SMS in", values, "YN_SMS");
            return (Criteria) this;
        }

        public Criteria andYN_SMSNotIn(List<String> values) {
            addCriterion("YN_SMS not in", values, "YN_SMS");
            return (Criteria) this;
        }

        public Criteria andYN_SMSBetween(String value1, String value2) {
            addCriterion("YN_SMS between", value1, value2, "YN_SMS");
            return (Criteria) this;
        }

        public Criteria andYN_SMSNotBetween(String value1, String value2) {
            addCriterion("YN_SMS not between", value1, value2, "YN_SMS");
            return (Criteria) this;
        }

        public Criteria andUPPER_NO_USERIsNull() {
            addCriterion("UPPER_NO_USER is null");
            return (Criteria) this;
        }

        public Criteria andUPPER_NO_USERIsNotNull() {
            addCriterion("UPPER_NO_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUPPER_NO_USEREqualTo(String value) {
            addCriterion("UPPER_NO_USER =", value, "UPPER_NO_USER");
            return (Criteria) this;
        }

        public Criteria andUPPER_NO_USERNotEqualTo(String value) {
            addCriterion("UPPER_NO_USER <>", value, "UPPER_NO_USER");
            return (Criteria) this;
        }

        public Criteria andUPPER_NO_USERGreaterThan(String value) {
            addCriterion("UPPER_NO_USER >", value, "UPPER_NO_USER");
            return (Criteria) this;
        }

        public Criteria andUPPER_NO_USERGreaterThanOrEqualTo(String value) {
            addCriterion("UPPER_NO_USER >=", value, "UPPER_NO_USER");
            return (Criteria) this;
        }

        public Criteria andUPPER_NO_USERLessThan(String value) {
            addCriterion("UPPER_NO_USER <", value, "UPPER_NO_USER");
            return (Criteria) this;
        }

        public Criteria andUPPER_NO_USERLessThanOrEqualTo(String value) {
            addCriterion("UPPER_NO_USER <=", value, "UPPER_NO_USER");
            return (Criteria) this;
        }

        public Criteria andUPPER_NO_USERLike(String value) {
            addCriterion("UPPER_NO_USER like", value, "UPPER_NO_USER");
            return (Criteria) this;
        }

        public Criteria andUPPER_NO_USERNotLike(String value) {
            addCriterion("UPPER_NO_USER not like", value, "UPPER_NO_USER");
            return (Criteria) this;
        }

        public Criteria andUPPER_NO_USERIn(List<String> values) {
            addCriterion("UPPER_NO_USER in", values, "UPPER_NO_USER");
            return (Criteria) this;
        }

        public Criteria andUPPER_NO_USERNotIn(List<String> values) {
            addCriterion("UPPER_NO_USER not in", values, "UPPER_NO_USER");
            return (Criteria) this;
        }

        public Criteria andUPPER_NO_USERBetween(String value1, String value2) {
            addCriterion("UPPER_NO_USER between", value1, value2, "UPPER_NO_USER");
            return (Criteria) this;
        }

        public Criteria andUPPER_NO_USERNotBetween(String value1, String value2) {
            addCriterion("UPPER_NO_USER not between", value1, value2, "UPPER_NO_USER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERIsNull() {
            addCriterion("DT_ENTER is null");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERIsNotNull() {
            addCriterion("DT_ENTER is not null");
            return (Criteria) this;
        }

        public Criteria andDT_ENTEREqualTo(String value) {
            addCriterion("DT_ENTER =", value, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERNotEqualTo(String value) {
            addCriterion("DT_ENTER <>", value, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERGreaterThan(String value) {
            addCriterion("DT_ENTER >", value, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERGreaterThanOrEqualTo(String value) {
            addCriterion("DT_ENTER >=", value, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERLessThan(String value) {
            addCriterion("DT_ENTER <", value, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERLessThanOrEqualTo(String value) {
            addCriterion("DT_ENTER <=", value, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERLike(String value) {
            addCriterion("DT_ENTER like", value, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERNotLike(String value) {
            addCriterion("DT_ENTER not like", value, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERIn(List<String> values) {
            addCriterion("DT_ENTER in", values, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERNotIn(List<String> values) {
            addCriterion("DT_ENTER not in", values, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERBetween(String value1, String value2) {
            addCriterion("DT_ENTER between", value1, value2, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_ENTERNotBetween(String value1, String value2) {
            addCriterion("DT_ENTER not between", value1, value2, "DT_ENTER");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATEIsNull() {
            addCriterion("DT_UPDATE is null");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATEIsNotNull() {
            addCriterion("DT_UPDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATEEqualTo(String value) {
            addCriterion("DT_UPDATE =", value, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATENotEqualTo(String value) {
            addCriterion("DT_UPDATE <>", value, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATEGreaterThan(String value) {
            addCriterion("DT_UPDATE >", value, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATEGreaterThanOrEqualTo(String value) {
            addCriterion("DT_UPDATE >=", value, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATELessThan(String value) {
            addCriterion("DT_UPDATE <", value, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATELessThanOrEqualTo(String value) {
            addCriterion("DT_UPDATE <=", value, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATELike(String value) {
            addCriterion("DT_UPDATE like", value, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATENotLike(String value) {
            addCriterion("DT_UPDATE not like", value, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATEIn(List<String> values) {
            addCriterion("DT_UPDATE in", values, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATENotIn(List<String> values) {
            addCriterion("DT_UPDATE not in", values, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATEBetween(String value1, String value2) {
            addCriterion("DT_UPDATE between", value1, value2, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_UPDATENotBetween(String value1, String value2) {
            addCriterion("DT_UPDATE not between", value1, value2, "DT_UPDATE");
            return (Criteria) this;
        }

        public Criteria andENTER_USERIsNull() {
            addCriterion("ENTER_USER is null");
            return (Criteria) this;
        }

        public Criteria andENTER_USERIsNotNull() {
            addCriterion("ENTER_USER is not null");
            return (Criteria) this;
        }

        public Criteria andENTER_USEREqualTo(String value) {
            addCriterion("ENTER_USER =", value, "ENTER_USER");
            return (Criteria) this;
        }

        public Criteria andENTER_USERNotEqualTo(String value) {
            addCriterion("ENTER_USER <>", value, "ENTER_USER");
            return (Criteria) this;
        }

        public Criteria andENTER_USERGreaterThan(String value) {
            addCriterion("ENTER_USER >", value, "ENTER_USER");
            return (Criteria) this;
        }

        public Criteria andENTER_USERGreaterThanOrEqualTo(String value) {
            addCriterion("ENTER_USER >=", value, "ENTER_USER");
            return (Criteria) this;
        }

        public Criteria andENTER_USERLessThan(String value) {
            addCriterion("ENTER_USER <", value, "ENTER_USER");
            return (Criteria) this;
        }

        public Criteria andENTER_USERLessThanOrEqualTo(String value) {
            addCriterion("ENTER_USER <=", value, "ENTER_USER");
            return (Criteria) this;
        }

        public Criteria andENTER_USERLike(String value) {
            addCriterion("ENTER_USER like", value, "ENTER_USER");
            return (Criteria) this;
        }

        public Criteria andENTER_USERNotLike(String value) {
            addCriterion("ENTER_USER not like", value, "ENTER_USER");
            return (Criteria) this;
        }

        public Criteria andENTER_USERIn(List<String> values) {
            addCriterion("ENTER_USER in", values, "ENTER_USER");
            return (Criteria) this;
        }

        public Criteria andENTER_USERNotIn(List<String> values) {
            addCriterion("ENTER_USER not in", values, "ENTER_USER");
            return (Criteria) this;
        }

        public Criteria andENTER_USERBetween(String value1, String value2) {
            addCriterion("ENTER_USER between", value1, value2, "ENTER_USER");
            return (Criteria) this;
        }

        public Criteria andENTER_USERNotBetween(String value1, String value2) {
            addCriterion("ENTER_USER not between", value1, value2, "ENTER_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USEREqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERLike(String value) {
            addCriterion("UPDATE_USER like", value, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andUPDATE_USERNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "UPDATE_USER");
            return (Criteria) this;
        }

        public Criteria andSTAT_MAILIsNull() {
            addCriterion("STAT_MAIL is null");
            return (Criteria) this;
        }

        public Criteria andSTAT_MAILIsNotNull() {
            addCriterion("STAT_MAIL is not null");
            return (Criteria) this;
        }

        public Criteria andSTAT_MAILEqualTo(String value) {
            addCriterion("STAT_MAIL =", value, "STAT_MAIL");
            return (Criteria) this;
        }

        public Criteria andSTAT_MAILNotEqualTo(String value) {
            addCriterion("STAT_MAIL <>", value, "STAT_MAIL");
            return (Criteria) this;
        }

        public Criteria andSTAT_MAILGreaterThan(String value) {
            addCriterion("STAT_MAIL >", value, "STAT_MAIL");
            return (Criteria) this;
        }

        public Criteria andSTAT_MAILGreaterThanOrEqualTo(String value) {
            addCriterion("STAT_MAIL >=", value, "STAT_MAIL");
            return (Criteria) this;
        }

        public Criteria andSTAT_MAILLessThan(String value) {
            addCriterion("STAT_MAIL <", value, "STAT_MAIL");
            return (Criteria) this;
        }

        public Criteria andSTAT_MAILLessThanOrEqualTo(String value) {
            addCriterion("STAT_MAIL <=", value, "STAT_MAIL");
            return (Criteria) this;
        }

        public Criteria andSTAT_MAILLike(String value) {
            addCriterion("STAT_MAIL like", value, "STAT_MAIL");
            return (Criteria) this;
        }

        public Criteria andSTAT_MAILNotLike(String value) {
            addCriterion("STAT_MAIL not like", value, "STAT_MAIL");
            return (Criteria) this;
        }

        public Criteria andSTAT_MAILIn(List<String> values) {
            addCriterion("STAT_MAIL in", values, "STAT_MAIL");
            return (Criteria) this;
        }

        public Criteria andSTAT_MAILNotIn(List<String> values) {
            addCriterion("STAT_MAIL not in", values, "STAT_MAIL");
            return (Criteria) this;
        }

        public Criteria andSTAT_MAILBetween(String value1, String value2) {
            addCriterion("STAT_MAIL between", value1, value2, "STAT_MAIL");
            return (Criteria) this;
        }

        public Criteria andSTAT_MAILNotBetween(String value1, String value2) {
            addCriterion("STAT_MAIL not between", value1, value2, "STAT_MAIL");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTIsNull() {
            addCriterion("NO_ACCT is null");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTIsNotNull() {
            addCriterion("NO_ACCT is not null");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTEqualTo(String value) {
            addCriterion("NO_ACCT =", value, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTNotEqualTo(String value) {
            addCriterion("NO_ACCT <>", value, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTGreaterThan(String value) {
            addCriterion("NO_ACCT >", value, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTGreaterThanOrEqualTo(String value) {
            addCriterion("NO_ACCT >=", value, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTLessThan(String value) {
            addCriterion("NO_ACCT <", value, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTLessThanOrEqualTo(String value) {
            addCriterion("NO_ACCT <=", value, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTLike(String value) {
            addCriterion("NO_ACCT like", value, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTNotLike(String value) {
            addCriterion("NO_ACCT not like", value, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTIn(List<String> values) {
            addCriterion("NO_ACCT in", values, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTNotIn(List<String> values) {
            addCriterion("NO_ACCT not in", values, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTBetween(String value1, String value2) {
            addCriterion("NO_ACCT between", value1, value2, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andNO_ACCTNotBetween(String value1, String value2) {
            addCriterion("NO_ACCT not between", value1, value2, "NO_ACCT");
            return (Criteria) this;
        }

        public Criteria andYN_DELIsNull() {
            addCriterion("YN_DEL is null");
            return (Criteria) this;
        }

        public Criteria andYN_DELIsNotNull() {
            addCriterion("YN_DEL is not null");
            return (Criteria) this;
        }

        public Criteria andYN_DELEqualTo(String value) {
            addCriterion("YN_DEL =", value, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELNotEqualTo(String value) {
            addCriterion("YN_DEL <>", value, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELGreaterThan(String value) {
            addCriterion("YN_DEL >", value, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELGreaterThanOrEqualTo(String value) {
            addCriterion("YN_DEL >=", value, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELLessThan(String value) {
            addCriterion("YN_DEL <", value, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELLessThanOrEqualTo(String value) {
            addCriterion("YN_DEL <=", value, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELLike(String value) {
            addCriterion("YN_DEL like", value, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELNotLike(String value) {
            addCriterion("YN_DEL not like", value, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELIn(List<String> values) {
            addCriterion("YN_DEL in", values, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELNotIn(List<String> values) {
            addCriterion("YN_DEL not in", values, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELBetween(String value1, String value2) {
            addCriterion("YN_DEL between", value1, value2, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andYN_DELNotBetween(String value1, String value2) {
            addCriterion("YN_DEL not between", value1, value2, "YN_DEL");
            return (Criteria) this;
        }

        public Criteria andTEL1IsNull() {
            addCriterion("TEL1 is null");
            return (Criteria) this;
        }

        public Criteria andTEL1IsNotNull() {
            addCriterion("TEL1 is not null");
            return (Criteria) this;
        }

        public Criteria andTEL1EqualTo(String value) {
            addCriterion("TEL1 =", value, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1NotEqualTo(String value) {
            addCriterion("TEL1 <>", value, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1GreaterThan(String value) {
            addCriterion("TEL1 >", value, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1GreaterThanOrEqualTo(String value) {
            addCriterion("TEL1 >=", value, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1LessThan(String value) {
            addCriterion("TEL1 <", value, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1LessThanOrEqualTo(String value) {
            addCriterion("TEL1 <=", value, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1Like(String value) {
            addCriterion("TEL1 like", value, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1NotLike(String value) {
            addCriterion("TEL1 not like", value, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1In(List<String> values) {
            addCriterion("TEL1 in", values, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1NotIn(List<String> values) {
            addCriterion("TEL1 not in", values, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1Between(String value1, String value2) {
            addCriterion("TEL1 between", value1, value2, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL1NotBetween(String value1, String value2) {
            addCriterion("TEL1 not between", value1, value2, "TEL1");
            return (Criteria) this;
        }

        public Criteria andTEL2IsNull() {
            addCriterion("TEL2 is null");
            return (Criteria) this;
        }

        public Criteria andTEL2IsNotNull() {
            addCriterion("TEL2 is not null");
            return (Criteria) this;
        }

        public Criteria andTEL2EqualTo(String value) {
            addCriterion("TEL2 =", value, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2NotEqualTo(String value) {
            addCriterion("TEL2 <>", value, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2GreaterThan(String value) {
            addCriterion("TEL2 >", value, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2GreaterThanOrEqualTo(String value) {
            addCriterion("TEL2 >=", value, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2LessThan(String value) {
            addCriterion("TEL2 <", value, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2LessThanOrEqualTo(String value) {
            addCriterion("TEL2 <=", value, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2Like(String value) {
            addCriterion("TEL2 like", value, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2NotLike(String value) {
            addCriterion("TEL2 not like", value, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2In(List<String> values) {
            addCriterion("TEL2 in", values, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2NotIn(List<String> values) {
            addCriterion("TEL2 not in", values, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2Between(String value1, String value2) {
            addCriterion("TEL2 between", value1, value2, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL2NotBetween(String value1, String value2) {
            addCriterion("TEL2 not between", value1, value2, "TEL2");
            return (Criteria) this;
        }

        public Criteria andTEL3IsNull() {
            addCriterion("TEL3 is null");
            return (Criteria) this;
        }

        public Criteria andTEL3IsNotNull() {
            addCriterion("TEL3 is not null");
            return (Criteria) this;
        }

        public Criteria andTEL3EqualTo(String value) {
            addCriterion("TEL3 =", value, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3NotEqualTo(String value) {
            addCriterion("TEL3 <>", value, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3GreaterThan(String value) {
            addCriterion("TEL3 >", value, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3GreaterThanOrEqualTo(String value) {
            addCriterion("TEL3 >=", value, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3LessThan(String value) {
            addCriterion("TEL3 <", value, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3LessThanOrEqualTo(String value) {
            addCriterion("TEL3 <=", value, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3Like(String value) {
            addCriterion("TEL3 like", value, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3NotLike(String value) {
            addCriterion("TEL3 not like", value, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3In(List<String> values) {
            addCriterion("TEL3 in", values, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3NotIn(List<String> values) {
            addCriterion("TEL3 not in", values, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3Between(String value1, String value2) {
            addCriterion("TEL3 between", value1, value2, "TEL3");
            return (Criteria) this;
        }

        public Criteria andTEL3NotBetween(String value1, String value2) {
            addCriterion("TEL3 not between", value1, value2, "TEL3");
            return (Criteria) this;
        }

        public Criteria andREG_IDIsNull() {
            addCriterion("REG_ID is null");
            return (Criteria) this;
        }

        public Criteria andREG_IDIsNotNull() {
            addCriterion("REG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andREG_IDEqualTo(String value) {
            addCriterion("REG_ID =", value, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDNotEqualTo(String value) {
            addCriterion("REG_ID <>", value, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDGreaterThan(String value) {
            addCriterion("REG_ID >", value, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDGreaterThanOrEqualTo(String value) {
            addCriterion("REG_ID >=", value, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDLessThan(String value) {
            addCriterion("REG_ID <", value, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDLessThanOrEqualTo(String value) {
            addCriterion("REG_ID <=", value, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDLike(String value) {
            addCriterion("REG_ID like", value, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDNotLike(String value) {
            addCriterion("REG_ID not like", value, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDIn(List<String> values) {
            addCriterion("REG_ID in", values, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDNotIn(List<String> values) {
            addCriterion("REG_ID not in", values, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDBetween(String value1, String value2) {
            addCriterion("REG_ID between", value1, value2, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andREG_IDNotBetween(String value1, String value2) {
            addCriterion("REG_ID not between", value1, value2, "REG_ID");
            return (Criteria) this;
        }

        public Criteria andCD_GRADEIsNull() {
            addCriterion("CD_GRADE is null");
            return (Criteria) this;
        }

        public Criteria andCD_GRADEIsNotNull() {
            addCriterion("CD_GRADE is not null");
            return (Criteria) this;
        }

        public Criteria andCD_GRADEEqualTo(String value) {
            addCriterion("CD_GRADE =", value, "CD_GRADE");
            return (Criteria) this;
        }

        public Criteria andCD_GRADENotEqualTo(String value) {
            addCriterion("CD_GRADE <>", value, "CD_GRADE");
            return (Criteria) this;
        }

        public Criteria andCD_GRADEGreaterThan(String value) {
            addCriterion("CD_GRADE >", value, "CD_GRADE");
            return (Criteria) this;
        }

        public Criteria andCD_GRADEGreaterThanOrEqualTo(String value) {
            addCriterion("CD_GRADE >=", value, "CD_GRADE");
            return (Criteria) this;
        }

        public Criteria andCD_GRADELessThan(String value) {
            addCriterion("CD_GRADE <", value, "CD_GRADE");
            return (Criteria) this;
        }

        public Criteria andCD_GRADELessThanOrEqualTo(String value) {
            addCriterion("CD_GRADE <=", value, "CD_GRADE");
            return (Criteria) this;
        }

        public Criteria andCD_GRADELike(String value) {
            addCriterion("CD_GRADE like", value, "CD_GRADE");
            return (Criteria) this;
        }

        public Criteria andCD_GRADENotLike(String value) {
            addCriterion("CD_GRADE not like", value, "CD_GRADE");
            return (Criteria) this;
        }

        public Criteria andCD_GRADEIn(List<String> values) {
            addCriterion("CD_GRADE in", values, "CD_GRADE");
            return (Criteria) this;
        }

        public Criteria andCD_GRADENotIn(List<String> values) {
            addCriterion("CD_GRADE not in", values, "CD_GRADE");
            return (Criteria) this;
        }

        public Criteria andCD_GRADEBetween(String value1, String value2) {
            addCriterion("CD_GRADE between", value1, value2, "CD_GRADE");
            return (Criteria) this;
        }

        public Criteria andCD_GRADENotBetween(String value1, String value2) {
            addCriterion("CD_GRADE not between", value1, value2, "CD_GRADE");
            return (Criteria) this;
        }

        public Criteria andYN_VISUALIsNull() {
            addCriterion("YN_VISUAL is null");
            return (Criteria) this;
        }

        public Criteria andYN_VISUALIsNotNull() {
            addCriterion("YN_VISUAL is not null");
            return (Criteria) this;
        }

        public Criteria andYN_VISUALEqualTo(String value) {
            addCriterion("YN_VISUAL =", value, "YN_VISUAL");
            return (Criteria) this;
        }

        public Criteria andYN_VISUALNotEqualTo(String value) {
            addCriterion("YN_VISUAL <>", value, "YN_VISUAL");
            return (Criteria) this;
        }

        public Criteria andYN_VISUALGreaterThan(String value) {
            addCriterion("YN_VISUAL >", value, "YN_VISUAL");
            return (Criteria) this;
        }

        public Criteria andYN_VISUALGreaterThanOrEqualTo(String value) {
            addCriterion("YN_VISUAL >=", value, "YN_VISUAL");
            return (Criteria) this;
        }

        public Criteria andYN_VISUALLessThan(String value) {
            addCriterion("YN_VISUAL <", value, "YN_VISUAL");
            return (Criteria) this;
        }

        public Criteria andYN_VISUALLessThanOrEqualTo(String value) {
            addCriterion("YN_VISUAL <=", value, "YN_VISUAL");
            return (Criteria) this;
        }

        public Criteria andYN_VISUALLike(String value) {
            addCriterion("YN_VISUAL like", value, "YN_VISUAL");
            return (Criteria) this;
        }

        public Criteria andYN_VISUALNotLike(String value) {
            addCriterion("YN_VISUAL not like", value, "YN_VISUAL");
            return (Criteria) this;
        }

        public Criteria andYN_VISUALIn(List<String> values) {
            addCriterion("YN_VISUAL in", values, "YN_VISUAL");
            return (Criteria) this;
        }

        public Criteria andYN_VISUALNotIn(List<String> values) {
            addCriterion("YN_VISUAL not in", values, "YN_VISUAL");
            return (Criteria) this;
        }

        public Criteria andYN_VISUALBetween(String value1, String value2) {
            addCriterion("YN_VISUAL between", value1, value2, "YN_VISUAL");
            return (Criteria) this;
        }

        public Criteria andYN_VISUALNotBetween(String value1, String value2) {
            addCriterion("YN_VISUAL not between", value1, value2, "YN_VISUAL");
            return (Criteria) this;
        }

        public Criteria andCNT_PW_ERRORIsNull() {
            addCriterion("CNT_PW_ERROR is null");
            return (Criteria) this;
        }

        public Criteria andCNT_PW_ERRORIsNotNull() {
            addCriterion("CNT_PW_ERROR is not null");
            return (Criteria) this;
        }

        public Criteria andCNT_PW_ERROREqualTo(Short value) {
            addCriterion("CNT_PW_ERROR =", value, "CNT_PW_ERROR");
            return (Criteria) this;
        }

        public Criteria andCNT_PW_ERRORNotEqualTo(Short value) {
            addCriterion("CNT_PW_ERROR <>", value, "CNT_PW_ERROR");
            return (Criteria) this;
        }

        public Criteria andCNT_PW_ERRORGreaterThan(Short value) {
            addCriterion("CNT_PW_ERROR >", value, "CNT_PW_ERROR");
            return (Criteria) this;
        }

        public Criteria andCNT_PW_ERRORGreaterThanOrEqualTo(Short value) {
            addCriterion("CNT_PW_ERROR >=", value, "CNT_PW_ERROR");
            return (Criteria) this;
        }

        public Criteria andCNT_PW_ERRORLessThan(Short value) {
            addCriterion("CNT_PW_ERROR <", value, "CNT_PW_ERROR");
            return (Criteria) this;
        }

        public Criteria andCNT_PW_ERRORLessThanOrEqualTo(Short value) {
            addCriterion("CNT_PW_ERROR <=", value, "CNT_PW_ERROR");
            return (Criteria) this;
        }

        public Criteria andCNT_PW_ERRORIn(List<Short> values) {
            addCriterion("CNT_PW_ERROR in", values, "CNT_PW_ERROR");
            return (Criteria) this;
        }

        public Criteria andCNT_PW_ERRORNotIn(List<Short> values) {
            addCriterion("CNT_PW_ERROR not in", values, "CNT_PW_ERROR");
            return (Criteria) this;
        }

        public Criteria andCNT_PW_ERRORBetween(Short value1, Short value2) {
            addCriterion("CNT_PW_ERROR between", value1, value2, "CNT_PW_ERROR");
            return (Criteria) this;
        }

        public Criteria andCNT_PW_ERRORNotBetween(Short value1, Short value2) {
            addCriterion("CNT_PW_ERROR not between", value1, value2, "CNT_PW_ERROR");
            return (Criteria) this;
        }

        public Criteria andYN_PW_ADMIN_INITIsNull() {
            addCriterion("YN_PW_ADMIN_INIT is null");
            return (Criteria) this;
        }

        public Criteria andYN_PW_ADMIN_INITIsNotNull() {
            addCriterion("YN_PW_ADMIN_INIT is not null");
            return (Criteria) this;
        }

        public Criteria andYN_PW_ADMIN_INITEqualTo(String value) {
            addCriterion("YN_PW_ADMIN_INIT =", value, "YN_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andYN_PW_ADMIN_INITNotEqualTo(String value) {
            addCriterion("YN_PW_ADMIN_INIT <>", value, "YN_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andYN_PW_ADMIN_INITGreaterThan(String value) {
            addCriterion("YN_PW_ADMIN_INIT >", value, "YN_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andYN_PW_ADMIN_INITGreaterThanOrEqualTo(String value) {
            addCriterion("YN_PW_ADMIN_INIT >=", value, "YN_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andYN_PW_ADMIN_INITLessThan(String value) {
            addCriterion("YN_PW_ADMIN_INIT <", value, "YN_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andYN_PW_ADMIN_INITLessThanOrEqualTo(String value) {
            addCriterion("YN_PW_ADMIN_INIT <=", value, "YN_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andYN_PW_ADMIN_INITLike(String value) {
            addCriterion("YN_PW_ADMIN_INIT like", value, "YN_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andYN_PW_ADMIN_INITNotLike(String value) {
            addCriterion("YN_PW_ADMIN_INIT not like", value, "YN_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andYN_PW_ADMIN_INITIn(List<String> values) {
            addCriterion("YN_PW_ADMIN_INIT in", values, "YN_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andYN_PW_ADMIN_INITNotIn(List<String> values) {
            addCriterion("YN_PW_ADMIN_INIT not in", values, "YN_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andYN_PW_ADMIN_INITBetween(String value1, String value2) {
            addCriterion("YN_PW_ADMIN_INIT between", value1, value2, "YN_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andYN_PW_ADMIN_INITNotBetween(String value1, String value2) {
            addCriterion("YN_PW_ADMIN_INIT not between", value1, value2, "YN_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_ADMIN_INITIsNull() {
            addCriterion("DT_PW_ADMIN_INIT is null");
            return (Criteria) this;
        }

        public Criteria andDT_PW_ADMIN_INITIsNotNull() {
            addCriterion("DT_PW_ADMIN_INIT is not null");
            return (Criteria) this;
        }

        public Criteria andDT_PW_ADMIN_INITEqualTo(String value) {
            addCriterion("DT_PW_ADMIN_INIT =", value, "DT_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_ADMIN_INITNotEqualTo(String value) {
            addCriterion("DT_PW_ADMIN_INIT <>", value, "DT_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_ADMIN_INITGreaterThan(String value) {
            addCriterion("DT_PW_ADMIN_INIT >", value, "DT_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_ADMIN_INITGreaterThanOrEqualTo(String value) {
            addCriterion("DT_PW_ADMIN_INIT >=", value, "DT_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_ADMIN_INITLessThan(String value) {
            addCriterion("DT_PW_ADMIN_INIT <", value, "DT_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_ADMIN_INITLessThanOrEqualTo(String value) {
            addCriterion("DT_PW_ADMIN_INIT <=", value, "DT_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_ADMIN_INITLike(String value) {
            addCriterion("DT_PW_ADMIN_INIT like", value, "DT_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_ADMIN_INITNotLike(String value) {
            addCriterion("DT_PW_ADMIN_INIT not like", value, "DT_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_ADMIN_INITIn(List<String> values) {
            addCriterion("DT_PW_ADMIN_INIT in", values, "DT_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_ADMIN_INITNotIn(List<String> values) {
            addCriterion("DT_PW_ADMIN_INIT not in", values, "DT_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_ADMIN_INITBetween(String value1, String value2) {
            addCriterion("DT_PW_ADMIN_INIT between", value1, value2, "DT_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_ADMIN_INITNotBetween(String value1, String value2) {
            addCriterion("DT_PW_ADMIN_INIT not between", value1, value2, "DT_PW_ADMIN_INIT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_UPDATEIsNull() {
            addCriterion("DT_PW_UPDATE is null");
            return (Criteria) this;
        }

        public Criteria andDT_PW_UPDATEIsNotNull() {
            addCriterion("DT_PW_UPDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDT_PW_UPDATEEqualTo(String value) {
            addCriterion("DT_PW_UPDATE =", value, "DT_PW_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_PW_UPDATENotEqualTo(String value) {
            addCriterion("DT_PW_UPDATE <>", value, "DT_PW_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_PW_UPDATEGreaterThan(String value) {
            addCriterion("DT_PW_UPDATE >", value, "DT_PW_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_PW_UPDATEGreaterThanOrEqualTo(String value) {
            addCriterion("DT_PW_UPDATE >=", value, "DT_PW_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_PW_UPDATELessThan(String value) {
            addCriterion("DT_PW_UPDATE <", value, "DT_PW_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_PW_UPDATELessThanOrEqualTo(String value) {
            addCriterion("DT_PW_UPDATE <=", value, "DT_PW_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_PW_UPDATELike(String value) {
            addCriterion("DT_PW_UPDATE like", value, "DT_PW_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_PW_UPDATENotLike(String value) {
            addCriterion("DT_PW_UPDATE not like", value, "DT_PW_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_PW_UPDATEIn(List<String> values) {
            addCriterion("DT_PW_UPDATE in", values, "DT_PW_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_PW_UPDATENotIn(List<String> values) {
            addCriterion("DT_PW_UPDATE not in", values, "DT_PW_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_PW_UPDATEBetween(String value1, String value2) {
            addCriterion("DT_PW_UPDATE between", value1, value2, "DT_PW_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_PW_UPDATENotBetween(String value1, String value2) {
            addCriterion("DT_PW_UPDATE not between", value1, value2, "DT_PW_UPDATE");
            return (Criteria) this;
        }

        public Criteria andDT_PW_NEXTIsNull() {
            addCriterion("DT_PW_NEXT is null");
            return (Criteria) this;
        }

        public Criteria andDT_PW_NEXTIsNotNull() {
            addCriterion("DT_PW_NEXT is not null");
            return (Criteria) this;
        }

        public Criteria andDT_PW_NEXTEqualTo(String value) {
            addCriterion("DT_PW_NEXT =", value, "DT_PW_NEXT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_NEXTNotEqualTo(String value) {
            addCriterion("DT_PW_NEXT <>", value, "DT_PW_NEXT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_NEXTGreaterThan(String value) {
            addCriterion("DT_PW_NEXT >", value, "DT_PW_NEXT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_NEXTGreaterThanOrEqualTo(String value) {
            addCriterion("DT_PW_NEXT >=", value, "DT_PW_NEXT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_NEXTLessThan(String value) {
            addCriterion("DT_PW_NEXT <", value, "DT_PW_NEXT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_NEXTLessThanOrEqualTo(String value) {
            addCriterion("DT_PW_NEXT <=", value, "DT_PW_NEXT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_NEXTLike(String value) {
            addCriterion("DT_PW_NEXT like", value, "DT_PW_NEXT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_NEXTNotLike(String value) {
            addCriterion("DT_PW_NEXT not like", value, "DT_PW_NEXT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_NEXTIn(List<String> values) {
            addCriterion("DT_PW_NEXT in", values, "DT_PW_NEXT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_NEXTNotIn(List<String> values) {
            addCriterion("DT_PW_NEXT not in", values, "DT_PW_NEXT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_NEXTBetween(String value1, String value2) {
            addCriterion("DT_PW_NEXT between", value1, value2, "DT_PW_NEXT");
            return (Criteria) this;
        }

        public Criteria andDT_PW_NEXTNotBetween(String value1, String value2) {
            addCriterion("DT_PW_NEXT not between", value1, value2, "DT_PW_NEXT");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_USER
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 24 11:42:50 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_USER
     *
     * @mbggenerated Tue Jun 24 11:42:50 KST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}