<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>

<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	
	<title>DzWeb</title>
	
	<%@ include file="../common/common.jsp"%>
	
	<style type="text/css">
		.ui-dialog-titlebar { display: none; }; 
	</style>
	
	<script type="text/javascript">
	
	$(document).ready(function() {
		
		/*
         * generated By JADI Generator
         * 다이알로그 셋팅
         * @since 1.0
         */
        $("#dialog1").dialog({
            height: 150,
            width: 300,
            autoOpen: false,
            buttons: {
                "확인": function () { fnClose(); },
                "닫기": function () { fnClose(); }
            }
        });
        $("#dialog2").dialog({
            height: 150,
            width: 300,
            autoOpen: false,
            buttons: {
                "확인": function () { $(this).dialog('close'); },
                "닫기": function () { $(this).dialog('close'); }
            }
        });
        $("#dialog3").dialog({
            height: 150,
            width: 300,
            autoOpen: false,
            buttons: {
                "확인": function () { $(this).dialog('close'); },
                "닫기": function () { $(this).dialog('close'); }
            }
        });
        $("#dialog4").dialog({
            height: 150,
            width: 300,
            autoOpen: false,
            buttons: {
                "확인": function () { $(this).dialog('close'); },
                "닫기": function () { $(this).dialog('close'); }
            }
        });
        $("#dialog5").dialog({
            height: 150,
            width: 300,
            autoOpen: false,
            buttons: {
                "확인": function () { $(this).dialog('close'); },
                "닫기": function () { $(this).dialog('close'); }
            }
        });
        $("#dialog6").dialog({
            height: 150,
            width: 300,
            autoOpen: false,
            buttons: {
                "확인": function () { $(this).dialog('close'); },
                "닫기": function () { $(this).dialog('close'); }
            }
        });
        $("#dialog7").dialog({
            height: 150,
            width: 300,
            autoOpen: false,
            buttons: {
                "확인": function () { $(this).dialog('close'); },
                "닫기": function () { $(this).dialog('close'); }
            }
        });
        $("#dialog8").dialog({
            height: 150,
            width: 300,
            autoOpen: false,
            buttons: {
                "확인": function () { $(this).dialog('close'); },
                "닫기": function () { $(this).dialog('close'); }
            }
        });
        $("#dialog9").dialog({
            height: 150,
            width: 300,
            autoOpen: false,
            buttons: {
                "확인": function () { $(this).dialog('close'); },
                "닫기": function () { $(this).dialog('close'); }
            }
        });
        $("#dialog10").dialog({
            height: 150,
            width: 300,
            autoOpen: false,
            buttons: {
                "확인": function () { $(this).dialog('close'); },
                "닫기": function () { $(this).dialog('close'); }
            }
        });
        $("#dialog11").dialog({
            height: 150,
            width: 300,
            autoOpen: false,
            buttons: {
                "확인": function () { $(this).dialog('close'); },
                "닫기": function () { $(this).dialog('close'); }
            }
        });
        $("#dialog_NoTitle").dialog({
            height: 150,
            width: 300,
            autoOpen: false,
            buttons: {
                "확인": function () { $(this).dialog('close'); },
                "닫기": function () { $(this).dialog('close'); }
            }
        });
        
        $("#btnDialog1").click(function (e) {
            $("#dialog1").dialog("open");
        });
        $("#btnDialog2").click(function (e) {
            $("#dialog2").dialog('option', 'show', 'blind');
            $("#dialog2").dialog('option', 'hide', 'blind');
            $("#dialog2").dialog("open");
        });
        $("#btnDialog3").click(function (e) {
            $("#dialog3").dialog('option', 'show', 'clip');
            $("#dialog3").dialog('option', 'hide', 'clip');
            $("#dialog3").dialog("open");
        });
        $("#btnDialog4").click(function (e) {
            $("#dialog4").dialog('option', 'show', 'drop');
            $("#dialog4").dialog('option', 'hide', 'drop');
            $("#dialog4").dialog("open");
        });
        $("#btnDialog5").click(function (e) {
            $("#dialog5").dialog('option', 'show', 'puff');
            $("#dialog5").dialog('option', 'hide', 'puff');
            $("#dialog5").dialog("open");
        });
        $("#btnDialog6").click(function (e) {
            $("#dialog6").dialog('option', 'show', 'slide');
            $("#dialog6").dialog('option', 'hide', 'slide');
            $("#dialog6").dialog("open");
        });
        $("#btnDialog7").click(function (e) {
            $("#dialog7").dialog('option', 'show', 'scale');
            $("#dialog7").dialog('option', 'hide', 'scale');
            $("#dialog7").dialog("open");
        });
        $("#btnDialog8").click(function (e) {
            $("#dialog8").dialog('option', 'show', 'size');
            $("#dialog8").dialog('option', 'hide', 'size');
            $("#dialog8").dialog("open");
        });
        $("#btnDialog9").click(function (e) {
            $("#dialog9").dialog('option', 'show', 'fade');
            $("#dialog9").dialog('option', 'hide', 'fade');
            $("#dialog9").dialog("open");
        });
        $("#btnDialog10").click(function (e) {
            $("#dialog10").dialog('option', 'show', 'bounce');
            $("#dialog10").dialog('option', 'hide', 'bounce');
            $("#dialog10").dialog("open");
        });
        $("#btnDialog11").click(function (e) {
            $("#dialog11").dialog('option', 'show', 'highlight');
            $("#dialog11").dialog('option', 'hide', 'highlight');
            $("#dialog11").dialog("open");
        });
        $("#btnDialog_NoTitle").click(function (e) {
            $("#dialog_NoTitle").dialog("open");
        });
        
        $("#btnDialog1").button();
        $("#btnDialog2").button();
        $("#btnDialog3").button();
        $("#btnDialog4").button();
        $("#btnDialog5").button();
        $("#btnDialog6").button();
        $("#btnDialog7").button();
        $("#btnDialog8").button();
        $("#btnDialog9").button();
        $("#btnDialog10").button();
        $("#btnDialog11").button();
        $("#btnDialog_NoTitle").button();


    });

    function fnClose() {
        $("#dialog1").dialog('close');
    }
	
	</script>
		
</head>

<body>

	<h4>다이얼로그</h4>
    
    <div>
        <input id="btnDialog1" type="button" value="click me!" />
        <input id="btnDialog2" type="button" value="blind" />
        <input id="btnDialog3" type="button" value="clip" />
        <input id="btnDialog4" type="button" value="drop" />
        <input id="btnDialog5" type="button" value="puff" />
        <input id="btnDialog6" type="button" value="slide" />
        <br />
        <br />
        <input id="btnDialog7" type="button" value="scale" />
        <input id="btnDialog8" type="button" value="size" />
        <input id="btnDialog9" type="button" value="fade" />
        <input id="btnDialog10" type="button" value="bounce" />
        <input id="btnDialog11" type="button" value="highlight" />
        <input id="btnDialog_NoTitle" type="button" value="타이틀 없음" />
    </div>
    
    <div id="dialog1" title="Dialog Title">
        I'm in a dialog
    </div>
    <div id="dialog2" title="Dialog Title">
        I'm in a dialog
    </div>
    <div id="dialog3" title="Dialog Title">
        I'm in a dialog
    </div>
    <div id="dialog4" title="Dialog Title">
        I'm in a dialog
    </div>
    <div id="dialog5" title="Dialog Title">
        I'm in a dialog
    </div>
    <div id="dialog6" title="Dialog Title">
        I'm in a dialog
    </div>
    <div id="dialog7" title="Dialog Title">
        I'm in a dialog
    </div>
    <div id="dialog8" title="Dialog Title">
        I'm in a dialog
    </div>
    <div id="dialog9" title="Dialog Title">
        I'm in a dialog
    </div>
    <div id="dialog10" title="Dialog Title">
        I'm in a dialog
    </div>
    <div id="dialog11" title="Dialog Title">
        I'm in a dialog
    </div>
    
    <div id="dialog_NoTitle" title="Dialog Title">
        I'm in a dialog
    </div>
    
</body>
</html>